/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare const enum BinaryFuncCode {
  PR = 'PR',
  RK = 'RK',
  SRK = 'SRK',
  NRTL = 'NRTL',
  NRTLRK = 'NRTLRK',
  WILSON = 'WILSON',
  UNIQUAC = 'UNIQUAC',
  PSRK = 'PSRK'
}

export interface ControlAndRateResult {
  id?: number
  controlParams: ControlParams
  rateParams: RateParams
}

export interface ControlParams {
  mode: string
  realFlag: number
  step: string
  acceleration: number
  currentTime: string
  endStep: number
  realFactor: number
  displayInterval: number
  simTime: number
  realTime: number
  runCount: number
  curTime: number
}

export interface FilterLabelParamsResult {
  filterLabelParams: Array<FilterLabelItem>
  rangeStatus: number
  showLabelParams: ShowLabelParams
}

export interface FullCacheData {
  id: number
  modelId: string
  objects: string
  sysvars: string
  updateAt: string
  simTime: string
  baseStateCode: string
  userName?: string
  stateIndex?: number
  stateDesc?: string
}

/** 页面使用的label, value 返回 */
export interface FunctionOptionDTO {
  label: string
  value: string
}

export interface RateParams {
  pfSolver: number
  controlAndLogic: number
  energyCalc: number
  flashCalc: number
}

export declare namespace autoShutter {
  export function syncCacheToLocalApi(): Promise<void>
  export function syncLocalToCacheApi(): Promise<void>
}

export declare namespace autoShutterCache {
  export interface AutoShutterData {
    objects: string
    sysvars: string
    simTime: string
    baseStateCode: string
  }
  export interface AutoShutterListItem {
    id: number
    updateAt: string
    simTime: string
    baseStateCode: string
  }
  /** 获取目前快照数量 */
  export function getAllModelAutoShutterCacheEntityCount(modelId: string): Promise<number>
  /** 查询缓存数据库中模型的数据 */
  export function getAllShutterCacheApiModelId(modelId: string): Promise<Array<FullCacheData>>
  /** 获取单个快照详情 (Service: get_model_auto_shutter_entity_by_id_cache) */
  export function getAutoShutterCacheDetailApi(id: number, modelId: string): Promise<FullCacheData>
  /** 获取快照列表 (Service: get_all_model_auto_shutter_entity_list_cache) */
  export function getAutoShutterCacheListApi(orderFlag: string, autoCount: number, modelId: string): Promise<Array<AutoShutterListItem>>
  /** 插入新的快照记录 (Service: insert_model_auto_shutter_entity_cache) */
  export function insertAutoShutterCacheApi(data: AutoShutterData, modelId: string): Promise<number>
  /** 批量插入数据到缓存数据库 (Service: read_model_auto_shutter_entity_cache) */
  export function readAutoShutterCacheApi(data: Array<FullCacheData>): Promise<void>
  /** 更新自动快照 (Service: update_model_auto_shutter_entity_cache) */
  export function updateAutoShutterCacheApi(data: AutoShutterData, modelId: string): Promise<number>
}

export declare namespace confConfig {
  export const enum ConfConfigValueTypeEnum {
    Json = 'Json',
    String = 'String',
    Number = 'Number'
  }
  export interface ConfigDTO {
    id: number
    name: string
    code: string
    value: string
    valueType: ConfConfigValueTypeEnum
  }
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getConfConfigAllMessageApi(): Promise<Array<ConfigDTO>>
  /** 批量更新或插入点位信息 */
  export function updateOrInsertConfConfigApi(data: Array<ConfigDTO>): Promise<number>
}

export declare namespace confFunctionPic {
  export interface FunctionPicDTO {
    id: number
    name: string
    picture: string
    code: string
  }
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getConfFunctionPicOneMessageApi(code: string): Promise<FunctionPicDTO>
  export interface NewFunctionPicDTO {
    name: string
    picture: string
    code: string
  }
  /** 批量更新或插入点位信息 */
  export function updateOrInsertConfFunctionPicApi(datas: Array<NewFunctionPicDTO>): Promise<void>
}

export declare namespace confGraphicCustom {
  export interface ConfGraphicCustomDTO {
    id: number
    name: string
    code: string
    customType: string
    arithmetic: string
    size: string
    svg: string
    ports: string
    windowSize: string
    dndType: string
  }
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getConfGraphicCustomOneMessageApi(): Promise<Array<ConfGraphicCustomDTO>>
  /** 批量更新或插入点位信息 */
  export function updateOrInsertConfGraphicCustomApi(data: Array<ConfGraphicCustomDTO>): Promise<number>
}

export declare namespace confModel {
  export interface ConfModelDTO {
    id: string
    createAt: string
    updateAt: string
    standardTemperature: number
    standardTemperatureUnit: string
    standardPressure: number
    standardPressureUnit: string
    gridSize: number
    gridColor: string
    gridState: string
    language: string
  }
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getConfModelAllMessageApi(): Promise<ConfModelDTO>
  /** 批量更新或插入点位信息 */
  export function updateOrInsertConfModelApi(data: ConfModelDTO): Promise<number>
}

export declare namespace confPfModelParams {
  export interface ConfPfModelParamsDto {
    id: number
    code: string
    name: string
    solverType: string
    params: string
  }
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getConfPfModelParamsAllMessageApi(): Promise<Array<ConfPfModelParamsDto>>
  /** 批量更新或插入点位信息 */
  export function updateOrInsertConfPfModelParamsApi(data: Array<ConfPfModelParamsDto>): Promise<number>
}

export declare namespace confSystemVariable {
  export interface ConfSystemVariableDto {
    id: number
    code: string
    name: string
    value: number
  }
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getConfSystemVariableOneMessageApi(): Promise<Array<ConfSystemVariableDto>>
  /** 批量更新或插入点位信息 */
  export function updateOrInsertConfSystemVariableApi(data: Array<ConfSystemVariableDto>): Promise<number>
}

export declare namespace confUnit {
  export interface ConfUnitFirstCategoryDTO {
    code: string
    name: string
    enName: string
  }
  export interface ConfUnitItemCategoryDTO {
    code: string
    name: string
    enName: string
    categorySecondCode: string
  }
  export interface ConfUnitItemDTO {
    id: number
    code: string
    value: string
    setCode: string
  }
  export interface ConfUnitSecondCategoryDTO {
    code: string
    name: string
    enName: string
    categoryFirstCode: string
  }
  export interface ConfUnitSetDTO {
    id: number
    code: string
    name: string
    enName: string
    status: number
    isDefault: number
  }
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getAllUnitFirstCategoryApi(): Promise<Array<ConfUnitFirstCategoryDTO>>
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getAllUnitItemApi(setCode: string): Promise<Array<ConfUnitItemDTO>>
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getAllUnitItemByCodesApi(setCode: string, codes: Array<string>): Promise<Array<ConfUnitItemDTO>>
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getAllUnitItemCategoryApi(): Promise<Array<ConfUnitItemCategoryDTO>>
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getAllUnitSecondCategoryApi(): Promise<Array<ConfUnitSecondCategoryDTO>>
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getAllUnitSetApi(): Promise<Array<ConfUnitSetDTO>>
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getOneUnitSetApi(code: string): Promise<ConfUnitSetDTO>
  /** 批量更新或插入点位信息 */
  export function updataAndInsertConfUnitFirstCategoryApi(data: Array<ConfUnitFirstCategoryDTO>): Promise<number>
  /** 批量更新或插入点位信息 */
  export function updataAndInsertConfUnitItemApi(data: Array<ConfUnitItemDTO>): Promise<number>
  /** 批量更新或插入点位信息 */
  export function updataAndInsertConfUnitItemCategoryApi(data: Array<ConfUnitItemCategoryDTO>): Promise<number>
  /** 批量更新或插入点位信息 */
  export function updataAndInsertConfUnitSecondCategoryApi(data: Array<ConfUnitSecondCategoryDTO>): Promise<number>
  /** 批量更新或插入点位信息 */
  export function updataAndInsertConfUnitSetApi(data: Array<ConfUnitSetDTO>): Promise<number>
}

export declare namespace heryDetail {
  export interface HenryDetailDTO {
    id: number
    componentI: string
    componentJ: string
    sourceName: string
    AIJ: number
    BIJ: number
    CIJ: number
    DIJ: number
    EIJ: number
    TLOWER: number
    TUPPER: number
    componentIId: number
    componentJId: number
  }
  /** 根据溶质(I)列表和溶剂(J)列表查询亨利常数记录 */
  export function queryPpComponentHenryDetailDataByIOrJApi(idsI: Array<string>, idsJ: Array<string>): Promise<Array<HenryDetailDTO>>
  /** 同步亨利详细数据 (包含差集删除、更新和插入) */
  export function syncPpHenryDetailDataApi(data: Array<any>): Promise<void>
}

export declare namespace initDB {
  /** 关闭数据库使用 */
  export function closeAllDbs(): Promise<void>
  /** 初始化自动快照数据库 */
  export function initAutoShutterDb(url: string): Promise<void>
  /** 初始化自动快照数据库 */
  export function initBusinessDb(url: string): Promise<void>
  /** 初始化缓存数据库 */
  export function initCacheDb(): Promise<void>
  /** 初始化自动快照数据库 */
  export function initConfigDb(url: string): Promise<void>
  /** 初始化自动快照数据库 */
  export function initPhysicalDb(url: string): Promise<void>
  /** 初始化快照数据库 */
  export function initShutterDb(url: string): Promise<void>
  /** 移动数据方法，目前只移动business数据库 */
  export function moveDbByUrl(targetPath: string): Promise<void>
}

export declare namespace modelConfig {
  export interface AutoShutterParams {
    autoShutter: number
    autoTimeInterval: number
    autoCount: number
  }
  export interface FilterLabelItem {
    id: number
    name: string
    key: string
    unitCode: string
    decimal: number
    svg: string
    location: string
    type: string
    show: boolean
  }
  export function getAutoShutterConfigApi(modelId: string): Promise<AutoShutterParams>
  export function getModelConfigByModelIdApi(modelId: string): Promise<ModelConfigDTO>
  export function getModelConfigControlAndRateApi(modelId: string): Promise<ControlAndRateResult>
  export function getModelConfigFilterLabelParamsApi(modelId: string): Promise<FilterLabelParamsResult>
  export function insertModelConfigApi(data: ModelConfigDTO): Promise<number>
  export interface ModelConfigDTO {
    id: number
    propertyParams: string
    controlParams: string
    rateParams: string
    flashParams: string
    modelId: string
    modelState: number
    filterLabelParams: string
    rangeStatus: number
    showLabelParams: string
    autoShutterParams: string
    oilParams: string
    relatePoint: string
    relateInterlock: string
    defaultParams: string
  }
  export interface ModelConfigUpdateDTO {
    id?: number
    propertyParams?: string
    controlParams?: string
    rateParams?: string
    flashParams?: string
    modelId: string
    modelState?: number
    filterLabelParams?: string
    rangeStatus?: number
    showLabelParams?: string
    autoShutterParams?: string
    oilParams?: string
    relatePoint?: string
    relateInterlock?: string
    defaultParams?: string
  }
  export interface ShowLabelParams {
    globalLabel: Array<FilterLabelItem>
    flowSheetLabel: Array<FilterLabelItem>
  }
  export function updateModelConfigByModelIdApi(modelId: string, data: ModelConfigUpdateDTO): Promise<string>
}

export declare namespace modelHandle {
  export function deleteModelByIdApi(id: string): Promise<number>
  export function getAllModelApi(): Promise<Array<ModelDTO>>
  export function getFirstModelByUpdateTimeApi(): Promise<ModelDTO>
  export function getModelByIdApi(id: string): Promise<ModelDTO>
  export function hasModelByIdApi(id: string): Promise<boolean>
  export function insertModelApi(modelData: ModelDTO): Promise<string>
  export interface ModelDTO {
    id: string
    modelNo: string
    developer: string
    modelName: string
    updateAt: string
    createAt: string
    status: number
    standardTemperature: number
    standardPressure: number
    gridState: string
    gridColor: string
    gridSize: number
    standardTemperatureUnit: string
    standardPressureUnit: string
    defaultModelId: string
  }
  export interface ModelUpdateDTO {
    id: string
    modelNo?: string
    developer?: string
    modelName?: string
    standardTemperature?: number
    standardPressure?: number
    gridState?: string
    gridColor?: string
    gridSize?: number
    standardTemperatureUnit?: string
    standardPressureUnit?: string
    defaultModelId?: string
    status?: number
  }
  export function selectModelByModelNameApi(name: string): Promise<string>
  export function selectModelByNoApi(modelNo: string): Promise<string>
  export function updateModelApi(modelData: ModelUpdateDTO): Promise<string>
}

export declare namespace physicalBinarySync {
  /** 批量查询接口 */
  export function queryBinaryDataApi(funcCode: string, ids: Array<string>): Promise<Array<any>>
  /** 批量同步接口 */
  export function syncBinaryDataApi(funcCode: string, data: Array<any>): Promise<void>
}

export declare namespace physicalCalc {
  /** 定一个整体联合查询的返回结果 */
  export interface CalcAllDetailDTO {
    basePropertyCode: string
    basePropertyId: number
    basePropertyName: string
    basePropertyKey: string
    basePropertyPhase: string
    basePropertyMixture: number
    calcFunctionCode: string
  }
  export interface CalcFunctionDTO {
    id: number
    name: string
    code: string
    argsJson: string
    isShow: number
  }
  /** 根据 ID 列表批量查询方法 */
  export function getAllPpCalcFunctionByIdsApi(ids: Array<number>): Promise<Array<CalcFunctionDTO>>
  /** 根据 Code 列表批量查询方法 */
  export function getFirstPpCalcFunctionByCodesApi(codes: Array<string>): Promise<Array<CalcFunctionDTO>>
  /** 根据方法 ID 获取流体包详细关联信息 */
  export function getFluidPackageAllBpByFunctionIdApi(functionId: number): Promise<Array<CalcAllDetailDTO>>
  /** 获取所有方法列表 */
  export function getPpCalcFunctionListApi(): Promise<Array<CalcFunctionDTO>>
  /** 根据 BasePhysicalId 获取 Function 选项 (用于下拉框) */
  export function getPpFunctionOptionsByBpIdApi(bpId: number): Promise<Array<FunctionOptionDTO>>
  /**
   * 批量初始化/同步物性计算相关消息数据
   * data_type: "basePhysical" | "function" | "relation"
   */
  export function initPpCalcAllMsgDataApi(dataType: string, data: Array<any>): Promise<void>
}

export declare namespace physicalComponent {
  /** 获取库中所有的组分信息列表 */
  export function getAllPhysicalInformationListApi(): Promise<Array<PhysicalInformationDTO>>
  /** 根据组分 ID (compound_id) 读取相关记录 */
  export function getPhysicalBaseByCompoundIdApi(compoundId: number): Promise<Array<PhysicalBaseDTO>>
  /** 根据 ID 列表批量获取组分基础物理性质 */
  export function getPhysicalBaseByIdsApi(ids: Array<number>): Promise<Array<PhysicalBaseDTO>>
  /** 根据 casNo 列表批量获取组分详细信息 */
  export function getPhysicalInformationListByCasNoListApi(casNoList: Array<string>): Promise<Array<PhysicalInformationDTO>>
  /** 根据 casNo 获取单条组分详细信息 */
  export function getPhysicalInformationOneByCasNoApi(casNo: string): Promise<PhysicalInformationDTO>
  /** 根据组分 ID (compound_id) 获取其所有的温度关联方程 */
  export function getPhysicalTemperatureEquationByCompoundIdApi(compoundId: number): Promise<Array<TemperatureEquationDTO>>
  /** 根据 ID 列表获取组分温度关联方程记录 */
  export function getPhysicalTemperatureEquationByIdsApi(ids: Array<number>): Promise<Array<TemperatureEquationDTO>>
  /** 快速初始化组分基础性质数据 (全量删除并重新分段插入) */
  export function initPhysicalBaseDataFastApi(initJsonData: Array<any>): Promise<void>
  /** 快速初始化组分信息数据 (全量清空并分段插入) */
  export function initPhysicalInformationDataFastApi(initJsonData: Array<any>): Promise<void>
  /** 快速初始化温度关联方程数据 (全量物理删除并分段插入) */
  export function initPhysicalTemperatureEquationDataFastApi(initJsonData: Array<any>): Promise<void>
  export interface PhysicalBaseDTO {
    id: number
    componentId: number
    code: string
    name: string
    refId: number
    value: number
    unitType: string
    isDefault: number
    isShow: number
  }
  export interface PhysicalInformationDTO {
    id: number
    name: string
    formula: string
    casNo: string
    number: number
    internalName: string
  }
  export interface TemperatureEquationDTO {
    id: number
    componentId: number
    code: string
    name: string
    unit: string
    functionCode: number
    functionName: string
    coefficientA: number
    coefficientB: number
    coefficientC: number
    coefficientD: number
    coefficientE: number
    coefficientF: number
    coefficientG: number
    coefficientH: number
    coefficientK: number
    coefficientL: number
    minApplicableTemperature: number
    minApplicableTemperatureUnit: string
    maxApplicableTemperature: number
    maxApplicableTemperatureUnit: string
    isDefault: number
    isShow: number
  }
}

export declare namespace pointInfor {
  /** 查询所有点位信息 (返回 JSON 字符串) */
  export function getPositionInformationCacheAllMessageApi(): Promise<Array<PositionData>>
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getPositionInformationCacheByTypesApi(types: Array<number>): Promise<Array<PositionData>>
  export interface PositionData {
    name: string
    nameDisplay: string
    typeName: string
    typeNum: number
  }
  /** 批量更新或插入点位信息 */
  export function updateOrInsertPositionInformationCacheApi(data: Array<PositionData>): Promise<void>
}

export declare namespace shutterHandle {
  /**
   * 删除快照信息 (deleteModelShutterEntity)
   * 签名: (id: string, modelId: string) => Promise<number> (返回 rows_affected)
   */
  export function deleteShutterEntity(id: string, modelId: string): Promise<number>
  export interface FullShutterData {
    id: string
    name: string
    indexNum: number
    modelId: string
    objects: string
    sysvars: string
    updateAt: string
    baseStateCode: string
    userName?: string
    stateIndex?: number
    stateDesc?: string
    typeNum?: number
  }
  export interface FullShutterModel {
    id: string
    name: string
    indexNum: number
    updateAt: string
    objects: string
    sysvars: string
    modelId: string
    userName?: string
    typeNum?: number
    stateIndex?: number
    stateDesc?: string
    baseStateCode: string
  }
  export function getAllShutterEntityDetailList(modelId: string): Promise<Array<FullShutterModel>>
  export function getAllShutterEntityList(modelId: string): Promise<Array<ShutterListItem>>
  export function getShutterEntityById(id: string, modelId: string): Promise<FullShutterData | null>
  export function getShutterEntityByIdOnly(id: string): Promise<FullShutterData | null>
  /** 创建/更新快照信息 (insertModelShutterEntity) */
  export function insertShutterEntity(data: FullShutterData, modelId: string): Promise<number>
  export function insertShutterEntityOnly(data: FullShutterData): Promise<void>
  export interface ShutterListItem {
    id: string
    name: string
    updateAt: string
    indexNum: number
    baseStateCode: string
  }
  export function updateShutterEntity(data: FullShutterData, modelId: string): Promise<number>
  /**
   * 根据 ID 更新部分信息 (updateModelShutterEntityByIndexOnly)
   * 签名: (id: string, objects: string, sysvars: string, status: string) => Promise<number> (返回 rows_affected)
   */
  export function updateShutterEntityByIdOnly(id: string, objects: string, sysvars: string, status: string): Promise<number>
}

export declare namespace undoRedoHandle {
  /** 增加一条记录 */
  export function addUndoLog(opType: string, tableName: string, oldData: string, newData: string, modelId: string): Promise<number>
  /** 清除已经使用过的信息，防止来回操作 */
  export function deleteUndoLogsById(id: number, modelId: string): Promise<boolean>
  /** 清除所有回撤记录 */
  export function deleteUndoLogsByModelId(modelId: string): Promise<boolean>
  export function getTheLastRedoModel(modelId: string): Promise<UndoRedoData>
  export function getTheLastUndoModel(modelId: string): Promise<UndoRedoData>
  /** 根据modelId获取撤回操作的所有信息 */
  export function listUndoLogs(modelId: string): Promise<Array<UndoRedoData>>
  export function test(): Promise<void>
  export interface UndoRedoData {
    id: number
    opType: string
    tableName: string
    oldData: string
    newData: string
    modelId: string
  }
  /** 更新一条信息状态 */
  export function updateUndoNewData(id: number, modelId: string, newData: string): Promise<void>
  /** 更新 状态，用于处理下一步操作 */
  export function updateUndoStatus(id: number, modelId: string, status: number): Promise<void>
}

export declare namespace variableCurveHandle {
  /** 插入新的变量曲线信息 */
  export function addVariableCurveLog(datasets: Array<DatasetItem>, modelId: string, configId: string, simTime: number): Promise<number>
  export interface CurveModel {
    id: number
    simTime: string
    datasets: string
    createAt: string
    modelId: string
    configId: string
  }
  export interface DatasetItem {
    id: string
    name: string
    value: string
  }
  /** 根据 modelId, configId 和时间间隔 filterCount 获取过滤后的曲线数据 */
  export function listVariableCurvesByFilterCount(modelId: string, configId: string, filterCount: number): Promise<Array<CurveModel>>
  /** 根据 modelId 和 configId 获取所有曲线数据，按时间排序 */
  export function listVariableCurvesByTime(modelId: string, configId: string): Promise<Array<CurveModel>>
}
