/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare namespace autoShutter {
  export function syncCacheToLocalApi(): Promise<void>
  export function syncLocalToCacheApi(): Promise<void>
}

export declare namespace autoShutterCache {
  export interface AutoShutterData {
    objects: string
    sysvars: string
    simTime: string
    baseStateCode: string
  }
  export interface AutoShutterListItem {
    id: number
    updateAt: string
    simTime: string
    baseStateCode: string
  }
  /** 获取目前快照数量 */
  export function getAllModelAutoShutterCacheEntityCount(modelId: string): Promise<number>
  /** 查询缓存数据库中模型的数据 */
  export function getAllShutterCacheApiModelId(modelId: string): Promise<Array<FullCacheData>>
  /** 获取单个快照详情 (Service: get_model_auto_shutter_entity_by_id_cache) */
  export function getAutoShutterCacheDetailApi(id: number, modelId: string): Promise<FullCacheData>
  /** 获取快照列表 (Service: get_all_model_auto_shutter_entity_list_cache) */
  export function getAutoShutterCacheListApi(orderFlag: string, autoCount: number, modelId: string): Promise<Array<AutoShutterListItem>>
  /** 插入新的快照记录 (Service: insert_model_auto_shutter_entity_cache) */
  export function insertAutoShutterCacheApi(data: AutoShutterData, modelId: string): Promise<number>
  /** 批量插入数据到缓存数据库 (Service: read_model_auto_shutter_entity_cache) */
  export function readAutoShutterCacheApi(data: Array<FullCacheData>): Promise<void>
  /** 更新自动快照 (Service: update_model_auto_shutter_entity_cache) */
  export function updateAutoShutterCacheApi(data: AutoShutterData, modelId: string): Promise<number>
}

export declare namespace confConfig {
  export const enum ConfConfigValueTypeEnum {
    Json = 'Json',
    String = 'String',
    Number = 'Number'
  }
  export interface ConfigDto {
    id: number
    name: string
    code: string
    value: string
    valueType: ConfConfigValueTypeEnum
  }
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getConfConfigAllMessageApi(): Promise<Array<ConfigDto>>
  /** 批量更新或插入点位信息 */
  export function updateOrInsertConfConfigApi(data: Array<ConfigDto>): Promise<number>
}

export declare namespace confFunctionPic {
  export interface FunctionPicDto {
    id: number
    name: string
    picture: string
    code: string
  }
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getConfFunctionPicOneMessageApi(code: string): Promise<FunctionPicDto>
  export interface NewFunctionPicDto {
    name: string
    picture: string
    code: string
  }
  /** 批量更新或插入点位信息 */
  export function updateOrInsertConfFunctionPicApi(datas: Array<NewFunctionPicDto>): Promise<void>
}

export declare namespace confGraphicCustom {
  export interface ConfGraphicCustomDto {
    id: number
    name: string
    code: string
    customType: string
    arithmetic: string
    size: string
    svg: string
    ports: string
    windowSize: string
    dndType: string
  }
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getConfGraphicCustomOneMessageApi(): Promise<Array<ConfGraphicCustomDto>>
  /** 批量更新或插入点位信息 */
  export function updateOrInsertConfGraphicCustomApi(data: Array<ConfGraphicCustomDto>): Promise<number>
}

export declare namespace confModel {
  export interface ConfModelDto {
    createAt: string
    updateAt: string
    standardTemperature: number
    standardTemperatureUnit: string
    standardPressure: number
    standardPressureUnit: string
    gridSize: string
    gridColor: string
    gridState: string
    language: string
  }
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getConfModelAllMessageApi(): Promise<ConfModelDto>
  /** 批量更新或插入点位信息 */
  export function updateOrInsertConfModelApi(data: ConfModelDto): Promise<number>
}

export declare namespace confPfModelParams {
  export interface ConfPfModelParamsDto {
    code: string
    name: string
    solverType: string
    params: string
  }
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getConfPfModelParamsAllMessageApi(): Promise<ConfPfModelParamsDto>
  /** 批量更新或插入点位信息 */
  export function updateOrInsertConfPfModelParamsApi(data: ConfPfModelParamsDto): Promise<number>
}

export declare namespace confSystemVariable {
  export interface ConfSystemVariableDto {
    code: string
    name: string
    value: number
  }
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getConfSystemVariableOneMessageApi(): Promise<Array<ConfSystemVariableDto>>
  /** 批量更新或插入点位信息 */
  export function updateOrInsertConfSystemVariableApi(data: Array<ConfSystemVariableDto>): Promise<number>
}

export declare namespace initDB {
  export function closeAllDbs(): Promise<void>
  /** 初始化自动快照数据库 */
  export function initAutoShutterDb(url: string): Promise<void>
  /** 初始化缓存数据库 */
  export function initCacheDb(): Promise<void>
  /** 初始化自动快照数据库 */
  export function initConfigDb(url: string): Promise<void>
  /** 初始化快照数据库 */
  export function initShutterDb(url: string): Promise<void>
}

export declare namespace pointInfor {
  /** 查询所有点位信息 (返回 JSON 字符串) */
  export function getPositionInformationCacheAllMessageApi(): Promise<Array<PositionData>>
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getPositionInformationCacheByTypesApi(types: Array<number>): Promise<Array<PositionData>>
  export interface PositionData {
    name: string
    nameDisplay: string
    typeName: string
    typeNum: number
  }
  /** 批量更新或插入点位信息 */
  export function updateOrInsertPositionInformationCacheApi(data: Array<PositionData>): Promise<void>
}

export declare namespace shutter {
  export interface FullCacheData {
    id: number
    modelId: string
    objects: string
    sysvars: string
    updateAt: string
    simTime: string
    baseStateCode: string
    userName?: string
    stateIndex?: number
    stateDesc?: string
  }
}

export declare namespace shutterHandle {
  /**
   * 删除快照信息 (deleteModelShutterEntity)
   * 签名: (id: string, modelId: string) => Promise<number> (返回 rows_affected)
   */
  export function deleteShutterEntity(id: string, modelId: string): Promise<number>
  export interface FullShutterData {
    id: string
    name: string
    indexNum: number
    modelId: string
    objects: string
    sysvars: string
    updateAt: string
    baseStateCode: string
    userName?: string
    stateIndex?: number
    stateDesc?: string
    typeNum?: number
  }
  export interface FullShutterModel {
    id: string
    name: string
    indexNum: number
    updateAt: string
    objects: string
    sysvars: string
    modelId: string
    userName?: string
    typeNum?: number
    stateIndex?: number
    stateDesc?: string
    baseStateCode: string
  }
  export function getAllShutterEntityDetailList(modelId: string): Promise<Array<FullShutterModel>>
  export function getAllShutterEntityList(modelId: string): Promise<Array<ShutterListItem>>
  /**
   * 获取一个快照信息 (getModelShutterEntityById)
   * 签名: (id: string, modelId: string) => Promise<FullCacheData | null>
   */
  export function getShutterEntityById(id: string, modelId: string): Promise<FullShutterData | null>
  /**
   * 获取一个快照信息 (getModelShutterEntityByIdOnly)
   * 签名: (id: string) => Promise<FullCacheData | null>
   */
  export function getShutterEntityByIdOnly(id: string): Promise<FullShutterData | null>
  /**
   * 创建/更新快照信息 (insertModelShutterEntity)
   * 检查 modelId 和 index 是否已存在，若存在则更新，否则插入新记录
   * 签名: (data: FullCacheData, modelId: string) => Promise<void>
   */
  export function insertShutterEntity(data: FullShutterData, modelId: string): Promise<number>
  /**
   * 仅创建快照信息 (insertModelShutterEntityOnly)
   * 签名: (data: FullCacheData) => Promise<void>
   */
  export function insertShutterEntityOnly(data: FullShutterData): Promise<void>
  export interface ShutterListItem {
    id: string
    name: string
    updateAt: string
    indexNum: number
    baseStateCode: string
  }
  export function updateShutterEntity(data: FullShutterData, modelId: string): Promise<number>
  /**
   * 根据 ID 更新部分信息 (updateModelShutterEntityByIndexOnly)
   * 签名: (id: string, objects: string, sysvars: string, status: string) => Promise<number> (返回 rows_affected)
   */
  export function updateShutterEntityByIdOnly(id: string, objects: string, sysvars: string, status: string): Promise<number>
}

export declare namespace undoRedoHandle {
  /** 增加一条记录 */
  export function addUndoLog(opType: string, tableName: string, oldData: string, newData: string, modelId: string): Promise<number>
  /** 清除已经使用过的信息，防止来回操作 */
  export function deleteUndoLogsById(id: number, modelId: string): Promise<boolean>
  /** 清除所有回撤记录 */
  export function deleteUndoLogsByModelId(modelId: string): Promise<boolean>
  export function getTheLastRedoModel(modelId: string): Promise<UndoRedoData>
  export function getTheLastUndoModel(modelId: string): Promise<UndoRedoData>
  /** 根据modelId获取撤回操作的所有信息 */
  export function listUndoLogs(modelId: string): Promise<Array<UndoRedoData>>
  export function test(): Promise<void>
  export interface UndoRedoData {
    id: number
    opType: string
    tableName: string
    oldData: string
    newData: string
    modelId: string
  }
  /** 更新一条信息状态 */
  export function updateUndoNewData(id: number, modelId: string, newData: string): Promise<void>
  /** 更新 状态，用于处理下一步操作 */
  export function updateUndoStatus(id: number, modelId: string, status: number): Promise<void>
}

export declare namespace variableCurveHandle {
  /** 插入新的变量曲线信息 */
  export function addVariableCurveLog(datasets: Array<DatasetItem>, modelId: string, configId: string, simTime: number): Promise<number>
  export interface CurveModel {
    id: number
    simTime: string
    datasets: string
    createAt: string
    modelId: string
    configId: string
  }
  export interface DatasetItem {
    id: string
    name: string
    value: string
  }
  /** 根据 modelId, configId 和时间间隔 filterCount 获取过滤后的曲线数据 */
  export function listVariableCurvesByFilterCount(modelId: string, configId: string, filterCount: number): Promise<Array<CurveModel>>
  /** 根据 modelId 和 configId 获取所有曲线数据，按时间排序 */
  export function listVariableCurvesByTime(modelId: string, configId: string): Promise<Array<CurveModel>>
}
