/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare const enum BinaryFuncCode {
  PR = 'PR',
  RK = 'RK',
  SRK = 'SRK',
  NRTL = 'NRTL',
  NRTLRK = 'NRTLRK',
  WILSON = 'WILSON',
  UNIQUAC = 'UNIQUAC',
  PSRK = 'PSRK'
}

export interface ControlParams {
  mode: string
  realFlag: number
  step: string
  acceleration: number
  currentTime: string
  endStep: number
  realFactor: number
  displayInterval: number
  simTime: number
  realTime: number
  runCount: number
  curTime: number
}

export interface FullCacheData {
  id: number
  modelId: string
  objects: string
  sysvars: string
  updateAt: string
  simTime: string
  baseStateCode: string
  userName?: string
  stateIndex?: number
  stateDesc?: string
}

/** 页面使用的label, value 返回 */
export interface FunctionOptionDTO {
  label: string
  value: string
}

export interface Model {
  id: string
  modelId: string
  name: string
  code: string
  value: number
  sortId: number
}

/** 核心函数：根据号段获取名称 (对应 TS 的 getGraphNameByNumberSegment) */
export interface NameResult {
  numberSegment: string
  name: string
}

export interface RateParams {
  pfSolver: number
  controlAndLogic: number
  energyCalc: number
  flashCalc: number
}

export declare namespace autoShutter {
  export interface AutoShutterData {
    objects: string
    sysvars: string
    simTime: string
    baseStateCode: string
  }
  export interface AutoShutterListItem {
    id: number
    updateAt: string
    simTime: string
    baseStateCode: string
  }
  /** 获取目前快照数量 */
  export function getAllModelAutoShutterCacheEntityCount(modelId: string): Promise<number>
  /** 查询缓存数据库中模型的数据 */
  export function getAllShutterCacheApiModelId(modelId: string): Promise<Array<FullCacheData>>
  /** 获取单个快照详情 (Service: get_model_auto_shutter_entity_by_id_cache) */
  export function getAutoShutterCacheDetailApi(id: number, modelId: string): Promise<FullCacheData>
  /** 获取快照列表 (Service: get_all_model_auto_shutter_entity_list_cache) */
  export function getAutoShutterCacheListApi(orderFlag: string, autoCount: number, modelId: string): Promise<Array<AutoShutterListItem>>
  /** 插入新的快照记录 (Service: insert_model_auto_shutter_entity_cache) */
  export function insertAutoShutterCacheApi(data: AutoShutterData, modelId: string): Promise<number>
  /** 更新自动快照 (Service: update_model_auto_shutter_entity_cache) */
  export function updateAutoShutterCacheApi(data: AutoShutterData, modelId: string): Promise<number>
}

export declare namespace confConfig {
  export const enum ConfConfigValueTypeEnum {
    Json = 'Json',
    String = 'String',
    Number = 'Number'
  }
  export interface ConfigDTO {
    id: number
    name: string
    code: string
    value: string
    valueType: ConfConfigValueTypeEnum
  }
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getConfConfigAllMessageApi(): Promise<Array<ConfigDTO>>
  /** 批量更新或插入点位信息 */
  export function updateOrInsertConfConfigApi(data: Array<ConfigDTO>): Promise<number>
}

export declare namespace confFunctionPic {
  export interface FunctionPicDTO {
    id: number
    name: string
    picture: string
    code: string
  }
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getConfFunctionPicOneMessageApi(code: string): Promise<FunctionPicDTO>
  export interface NewFunctionPicDTO {
    name: string
    picture: string
    code: string
  }
  /** 批量更新或插入点位信息 */
  export function updateOrInsertConfFunctionPicApi(datas: Array<NewFunctionPicDTO>): Promise<void>
}

export declare namespace confGraphicCustom {
  export interface ConfGraphicCustomDTO {
    id: number
    name: string
    code: string
    customType: string
    arithmetic: string
    size: string
    svg: string
    ports: string
    windowSize: string
    dndType: string
  }
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getConfGraphicCustomOneMessageApi(): Promise<Array<ConfGraphicCustomDTO>>
  /** 批量更新或插入点位信息 */
  export function updateOrInsertConfGraphicCustomApi(data: Array<ConfGraphicCustomDTO>): Promise<number>
}

export declare namespace confModel {
  export interface ConfModelDTO {
    id: string
    createAt: string
    updateAt: string
    standardTemperature: number
    standardTemperatureUnit: string
    standardPressure: number
    standardPressureUnit: string
    gridSize: number
    gridColor: string
    gridState: string
    language: string
  }
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getConfModelAllMessageApi(): Promise<ConfModelDTO>
  /** 批量更新或插入点位信息 */
  export function updateOrInsertConfModelApi(data: ConfModelDTO): Promise<number>
}

export declare namespace confPfModelParams {
  export interface ConfPfModelParamsDto {
    id: number
    code: string
    name: string
    solverType: string
    params: string
  }
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getConfPfModelParamsAllMessageApi(): Promise<Array<ConfPfModelParamsDto>>
  /** 批量更新或插入点位信息 */
  export function updateOrInsertConfPfModelParamsApi(data: Array<ConfPfModelParamsDto>): Promise<number>
}

export declare namespace confSystemVariable {
  export interface ConfSystemVariableDto {
    id: number
    code: string
    name: string
    value: number
  }
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getConfSystemVariableOneMessageApi(): Promise<Array<ConfSystemVariableDto>>
  /** 批量更新或插入点位信息 */
  export function updateOrInsertConfSystemVariableApi(data: Array<ConfSystemVariableDto>): Promise<number>
}

export declare namespace confUnit {
  export interface ConfUnitFirstCategoryDTO {
    code: string
    name: string
    enName: string
  }
  export interface ConfUnitItemCategoryDTO {
    code: string
    name: string
    enName: string
    categorySecondCode: string
  }
  export interface ConfUnitItemDTO {
    id: number
    code: string
    value: string
    setCode: string
  }
  export interface ConfUnitSecondCategoryDTO {
    code: string
    name: string
    enName: string
    categoryFirstCode: string
  }
  export interface ConfUnitSetDTO {
    id: number
    code: string
    name: string
    enName: string
    status: number
    isDefault: number
  }
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getAllUnitFirstCategoryApi(): Promise<Array<ConfUnitFirstCategoryDTO>>
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getAllUnitItemApi(setCode: string): Promise<Array<ConfUnitItemDTO>>
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getAllUnitItemByCodesApi(setCode: string, codes: Array<string>): Promise<Array<ConfUnitItemDTO>>
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getAllUnitItemCategoryApi(): Promise<Array<ConfUnitItemCategoryDTO>>
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getAllUnitSecondCategoryApi(): Promise<Array<ConfUnitSecondCategoryDTO>>
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getAllUnitSetApi(): Promise<Array<ConfUnitSetDTO>>
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getOneUnitSetApi(code: string): Promise<ConfUnitSetDTO>
  /** 批量更新或插入点位信息 */
  export function updataAndInsertConfUnitFirstCategoryApi(data: Array<ConfUnitFirstCategoryDTO>): Promise<number>
  /** 批量更新或插入点位信息 */
  export function updataAndInsertConfUnitItemApi(data: Array<ConfUnitItemDTO>): Promise<number>
  /** 批量更新或插入点位信息 */
  export function updataAndInsertConfUnitItemCategoryApi(data: Array<ConfUnitItemCategoryDTO>): Promise<number>
  /** 批量更新或插入点位信息 */
  export function updataAndInsertConfUnitSecondCategoryApi(data: Array<ConfUnitSecondCategoryDTO>): Promise<number>
  /** 批量更新或插入点位信息 */
  export function updataAndInsertConfUnitSetApi(data: Array<ConfUnitSetDTO>): Promise<number>
}

export declare namespace heryDetail {
  export interface HenryDetailDTO {
    id: number
    componentI: string
    componentJ: string
    sourceName: string
    AIJ: number
    BIJ: number
    CIJ: number
    DIJ: number
    EIJ: number
    TLOWER: number
    TUPPER: number
    componentIId: number
    componentJId: number
  }
  /** 根据溶质(I)列表和溶剂(J)列表查询亨利常数记录 */
  export function queryPpComponentHenryDetailDataByIOrJApi(idsI: Array<string>, idsJ: Array<string>): Promise<Array<HenryDetailDTO>>
  /** 同步亨利详细数据 (包含差集删除、更新和插入) */
  export function syncPpHenryDetailDataApi(data: Array<any>): Promise<void>
}

export declare namespace initDB {
  /** 关闭数据库使用 */
  export function closeAllDbs(): Promise<void>
  export interface DbStats {
    activeConnections: number
    idleConnections: number
    memoryUsedBytes: number
  }
  export function getCacheDbStatsApi(): Promise<DbStats>
  /** 初始化自动快照数据库 */
  export function initAutoShutterDb(url: string): Promise<void>
  /** 初始化自动快照数据库 */
  export function initBusinessDb(url: string): Promise<void>
  /** 初始化缓存数据库 */
  export function initCacheDb(): Promise<void>
  /** 初始化自动快照数据库 */
  export function initConfigDb(url: string): Promise<void>
  /** 初始化自动快照数据库 */
  export function initPhysicalDb(url: string): Promise<void>
  /** 初始化快照数据库 */
  export function initShutterDb(url: string): Promise<void>
  /** 移动数据方法，目前只移动business数据库 */
  export function moveDbByUrl(targetPath: string): Promise<void>
}

export declare namespace modelComponentChannel {
  export function deleteComponentChannelByIdsApi(ids: Array<string>): Promise<number>
  export function getAllComponentChannelByIdsApi(ids: Array<string>): Promise<Array<ModelComponentChannelDTO>>
  export function getAllComponentChannelByModelIdApi(modelId: string): Promise<Array<ModelComponentChannelDTO>>
  export function getComponentChannelByModelFirstApi(modelId: string): Promise<ModelComponentChannelDTO>
  export function getFirstComponentChannelApi(id: string, modelId: string): Promise<ModelComponentChannelDTO | null>
  export function insertComponentChannelApi(data: ModelComponentChannelDTO): Promise<string>
  export function insertComponentChannelsCopyApi(datas: Array<ModelComponentChannelDTO>): Promise<boolean>
  export interface ModelComponentChannelDTO {
    id: string
    refName: string
    name: string
    modelId: string
  }
  export interface ModelComponentChannelUpdateDTO {
    id: string
    refName?: string
    name?: string
  }
  export function selectComponentChannelByNameCountApi(name: string, modelId: string): Promise<boolean>
  export function selectComponentChannelByNameLikeApi(name: string, modelId: string): Promise<Array<ModelComponentChannelDTO>>
  export function updateComponentChannelApi(data: ModelComponentChannelUpdateDTO, modelId: string): Promise<string>
}

export declare namespace modelComponentDetail {
  export interface ComponentCasNoNameDTO {
    casNo: string
    name: string
    internalName: string
  }
  export interface ComponentNormalDTO {
    casNo: string
    name: string
    id: string
    sourceId: string
    sourceType: string
  }
  export function deleteComponentAllDetailByChannelIdsApi(channelIds: Array<string>): Promise<number>
  export function deleteComponentAllDetailByIdsApi(ids: Array<string>): Promise<number>
  export function findComponentAllDetailByIdsApi(ids: Array<string>): Promise<Array<ModelComponentAllDetailDTO>>
  export function findComponentAllDetailCasnoByIdsApi(ids: Array<string>): Promise<Array<string>>
  export function getAllComponentDetailByChannelIdApi(channelId: string): Promise<Array<ModelComponentAllDetailDTO>>
  export function getAllDetailByChannelIdVecApi(channelId: Array<string>): Promise<Array<ModelComponentAllDetailDTO>>
  export function getAllModelComponentChannelCountApi(channelId: string): Promise<number>
  export function getComponentNormalDetailApi(channelId: string): Promise<Array<ComponentNormalDTO>>
  export function getComponentNormalDetailNameCasnoApi(channelId: string): Promise<Array<ComponentCasNoNameDTO>>
  export function getOneAllComponentDetailByIdApi(id: string): Promise<ModelComponentAllDetailDTO | null>
  export function insertModelComponentAllDetailListApi(list: Array<ModelComponentAllDetailDTO>): Promise<number>
  export interface ModelComponentAllDetailDTO {
    id: string
    sourceId: string
    sourceType: string
    name: string
    formula: string
    casNo: string
    baseCasNo: string
    number: number
    internalName: string
    sortNum: number
    compoundChannelId: string
    basePhysicalProperty: string
    temperatureEquationProperty: string
  }
  export interface ModelComponentAllDetailUpdateDTO {
    id: string
    sourceId?: string
    sourceType?: string
    name?: string
    formula?: string
    casNo?: string
    baseCasNo?: string
    number?: number
    internalName?: string
    sortNum?: number
    compoundChannelId?: string
    basePhysicalProperty?: string
    temperatureEquationProperty?: string
  }
  export function selectComponentAllDetailHaveByNameApi(name: string, channelId: string): Promise<boolean>
  export function updateComponentPhysicalDataApi(id: string, base: string, temp: string): Promise<number>
  export function updateModelComponentAllDetailOptionApi(updateData: ModelComponentAllDetailUpdateDTO): Promise<string>
}

export declare namespace modelComponentHenry {
  export interface ComponentHenryConnectDTO {
    componentHenryId: string
    componentDetailIds: Array<string | undefined | null>
  }
  export function deleteByComponentChannelIdsApi(channelIds: Array<string>): Promise<number>
  export function deleteComponentHenryByIdsApi(ids: Array<string>): Promise<number>
  export function getModelComponentHenryByIdApi(id: string): Promise<ModelComponentHenryDTO>
  export function getModelComponentHenryByIdsApi(ids: Array<string>): Promise<Array<ModelComponentHenryDTO>>
  export function henryConnectComponentDetailApi(msg: ComponentHenryConnectDTO): Promise<number>
  export function insertComponentHenryListApi(list: Array<ModelComponentHenryDTO>): Promise<number>
  export interface ModelComponentHenryDTO {
    id: string
    name: string
    compoundChannelId: string
    compoundDetailIds: string
  }
  export function selectByComponentChannelIdApi(channelId: string): Promise<Array<ModelComponentHenryDTO>>
  export function selectByComponentChannelIdsApi(channelIds: Array<string>): Promise<Array<ModelComponentHenryDTO>>
  export function selectComponentHenryByNameApi(name: string, channelId: string): Promise<boolean>
  export function updateComponentHenryNameApi(id: string, name: string): Promise<boolean>
}

export declare namespace modelComponentHenryDetail {
  export function deleteCompoundHenryDetailByCasnoApi(casnos: Array<string>, henryId: string): Promise<number>
  export function deleteCompoundHenryDetailByHenryIdsApi(henryIds: Array<string>): Promise<number>
  export function deleteCompoundHenryDetailByIdsApi(ids: Array<string>): Promise<number>
  export function insertCompoundHenryDetailListApi(list: Array<ModelComponentHenryDetailDTO>): Promise<number>
  export interface ModelComponentHenryDetailDTO {
    id: string
    isDefaultId: string
    componentIId: number
    componentI: string
    componentJId: number
    componentJ: string
    sourceName: string
    aij: number
    bij: number
    cij: number
    dij: number
    eij: number
    tlower: number
    tupper: number
    isDefault: number
    compoundHenryId: string
  }
  export function selectCompoundHenryDetailByHenryIdApi(henryId: string, isDefault: number): Promise<Array<ModelComponentHenryDetailDTO>>
  export function selectCompoundHenryDetailByHenryIdsApi(henryIds: Array<string>, isDefault: number): Promise<Array<ModelComponentHenryDetailDTO>>
  export function selectCompoundHenryDetailByIdsApi(ids: Array<string>): Promise<Array<ModelComponentHenryDetailDTO>>
  export function selectCompoundHenryDetailByOnlyHenryIdsApi(ids: Array<string>): Promise<Array<ModelComponentHenryDetailDTO>>
  export function updateCompoundHenryDetailApi(data: ModelComponentHenryDetailDTO): Promise<string>
}

export declare namespace modelComponentOil {
  export function deleteModelComponentOilsByChannelIdsApi(channelIds: Array<string>): Promise<number>
  export function deleteModelComponentOilsByIdsApi(ids: Array<string>): Promise<number>
  export function getModelComponentOilByIdApi(id: string): Promise<ModelComponentOilDTO | null>
  export function getOilsByChannelIdApi(channelId: string): Promise<Array<ModelComponentOilDTO>>
  export function getOilsByChannelIdsApi(channelIds: Array<string>): Promise<Array<ModelComponentOilDTO>>
  export function getOilsByComponentCasNoApi(casNo: Array<string>): Promise<Array<ModelComponentOilDTO>>
  export function insertModelComponentOilApi(list: Array<ModelComponentOilDTO>): Promise<number>
  export interface ModelComponentOilDTO {
    id: string
    compoundChannelId: string
    name: string
    internalName: string
    formula: string
    casNo: string
    group: number
    basePhysicalProperty: string
    defaultPhysicalProperty: string
    temperatureEquationProperty: string
  }
  export interface ModelComponentOilUpdateDTO {
    id: string
    compoundChannelId?: string
    name?: string
    internalName?: string
    formula?: string
    casNo?: string
    group?: number
    basePhysicalProperty?: string
    defaultPhysicalProperty?: string
    temperatureEquationProperty?: string
  }
  export function updateModelComponentOilApi(data: ModelComponentOilUpdateDTO): Promise<string>
  export function updateModelCompoundOilsApi(list: Array<ModelComponentOilUpdateDTO>): Promise<Array<string>>
}

export declare namespace modelConfig {
  export interface AutoShutterParams {
    autoShutter: number
    autoTimeInterval: number
    autoCount: number
  }
  export interface ControlAndRateResult {
    id?: number
    controlParams: ControlParams
    rateParams: RateParams
  }
  export interface FilterLabelItem {
    id: number
    name: string
    key: string
    unitCode: string
    decimal: number
    svg: string
    location: string
    type: string
    show: boolean
  }
  export interface FilterLabelParamsResult {
    filterLabelParams: Array<FilterLabelItem>
    rangeStatus: number
    showLabelParams: ShowLabelParams
  }
  export function getAutoShutterConfigApi(modelId: string): Promise<AutoShutterParams>
  export function getModelConfigByModelIdApi(modelId: string): Promise<ModelConfigDTO>
  export function getModelConfigControlAndRateApi(modelId: string): Promise<ControlAndRateResult>
  export function getModelConfigFilterLabelParamsApi(modelId: string): Promise<FilterLabelParamsResult>
  export function getShowLabelParamsConfigApi(modelId: string): Promise<ShowLabelParams>
  export function insertModelConfigApi(data: ModelConfigDTO): Promise<number>
  export interface ModelConfigDTO {
    id: number
    propertyParams: string
    controlParams: string
    rateParams: string
    flashParams: string
    modelId: string
    modelState: number
    filterLabelParams: string
    rangeStatus: number
    showLabelParams: string
    autoShutterParams: string
    oilParams: string
    relatePoint: string
    relateInterlock: string
    defaultParams: string
  }
  export interface ModelConfigUpdateDTO {
    id?: number
    propertyParams?: string
    controlParams?: string
    rateParams?: string
    flashParams?: string
    modelId: string
    modelState?: number
    filterLabelParams?: string
    rangeStatus?: number
    showLabelParams?: string
    autoShutterParams?: string
    oilParams?: string
    relatePoint?: string
    relateInterlock?: string
    defaultParams?: string
  }
  export interface ShowLabelParams {
    globalLabel: Array<FilterLabelItem>
    flowSheetLabel: Array<FilterLabelItem>
  }
  export function updateModelConfigByModelIdApi(modelId: string, data: ModelConfigUpdateDTO): Promise<string>
}

export declare namespace modelHandle {
  export function deleteModelByIdApi(id: string): Promise<number>
  export function getAllModelApi(): Promise<Array<ModelDTO>>
  export function getFirstModelByUpdateTimeApi(): Promise<ModelDTO>
  export function getModelByIdApi(id: string): Promise<ModelDTO>
  export function hasModelByIdApi(id: string): Promise<boolean>
  export function insertModelApi(modelData: ModelDTO): Promise<string>
  export interface ModelDTO {
    id: string
    modelNo: string
    developer: string
    modelName: string
    updateAt: string
    createAt: string
    status: number
    standardTemperature: number
    standardPressure: number
    gridState: string
    gridColor: string
    gridSize: number
    standardTemperatureUnit: string
    standardPressureUnit: string
    defaultModelId: string
  }
  export interface ModelUpdateDTO {
    id: string
    modelNo?: string
    developer?: string
    modelName?: string
    standardTemperature?: number
    standardPressure?: number
    gridState?: string
    gridColor?: string
    gridSize?: number
    standardTemperatureUnit?: string
    standardPressureUnit?: string
    defaultModelId?: string
    status?: number
  }
  export function selectModelByModelNameApi(name: string): Promise<string>
  export function selectModelByNoApi(modelNo: string): Promise<string>
  export function updateModelApi(modelData: ModelUpdateDTO): Promise<string>
}

export declare namespace modelSystem {
  export function getSystemDetailApi(modelId: string): Promise<Array<ModelSystemVariableDTO>>
  export function initModelSystemVariableApi(systems: Array<ModelSystemVariableDTO>, modelId: string): Promise<boolean>
  export interface ModelSystemVariableDTO {
    id: string
    modelId: string
    name: string
    code: string
    value: number
    sortId: number
  }
  export function updateSystemDetailApi(systems: Array<ModelSystemVariableDTO>): Promise<boolean>
}

export declare namespace modelUnit {
  /** 删除单位集及其关联项 */
  export function deleteAllModelUnitByIdApi(id: string): Promise<number>
  /** 通过set_id获取所有的item信息 */
  export function getModelUnitItemsBySetIdAndModelIdApi(setId: string, modelId: string): Promise<Array<ModelUnitItemDTO>>
  export function getModelUnitSetAllByModelIdApi(modelId: string): Promise<Array<ModelUnitSetDTO>>
  export function getModelUnitSetItemsByCodesAndSetIdApi(codes: Array<string>, setId: string, modelId: string): Promise<Array<ModelUnitItemDTO>>
  export function getModelUnitSetItemsByModelIdApi(modelId: string): Promise<Array<ModelUnitItemDTO>>
  export function getModelUnitSetOneByIdApi(id: string): Promise<ModelUnitSetDTO>
  export function getModelUnitSetOneByModelIdAndDefaultApi(modelId: string): Promise<ModelUnitSetDTO>
  export function getModelUnitSetWithItemsApi(id: string): Promise<UnitFullDataDTO>
  /** 插入完整的单位集合及所有 Items */
  export function insertModelUnitModelFullApi(setData: ModelUnitSetDTO, items: Array<ModelUnitItemDTO>): Promise<string>
  export function insertModelUnitSetOnlyApi(unitSet: Array<ModelUnitSetDTO>): Promise<boolean>
  export interface ModelUnitItemDTO {
    id: string
    setId: string
    modelId: string
    code: string
    value: string
  }
  export interface ModelUnitSetDTO {
    id: string
    modelId: string
    enName: string
    name: string
    code: string
    status: number
    isDefault: number
  }
  export interface ModelUnitSetItemsUpdateDTO {
    id: string
    enName: string
    name: string
    code: string
    status: number
    modelId: string
    isDefault: number
    items: Array<ModelUnitItemDTO>
  }
  export interface ModelUnitSetUpdateDTO {
    id: string
    modelId: string
    enName?: string
    name?: string
    code?: string
    status?: number
    isDefault?: number
  }
  export interface UnitFullDataDTO {
    set: ModelUnitSetDTO
    items: Array<ModelUnitItemDTO>
  }
  /** 更新单位集基本信息（如 Code）并循环更新所有关联项的 Value */
  export function updateModelUnitAllItemsApi(unitSet: ModelUnitSetItemsUpdateDTO, modelId: string): Promise<boolean>
  /** 增量更新单位集合信息（含默认值排他性逻辑） */
  export function updateModelUnitSetLogicApi(data: ModelUnitSetUpdateDTO): Promise<boolean>
}

export declare namespace model_type {
  /** 自定义节点名称 */
  export const enum CustomNodeName {
    ScriptLogic = '脚本逻辑',
    ScriptUO = '脚本模块',
    CustomUserUO = '自定义算法',
    CustomUserLogic0 = '电加热',
    CustomUserLogic1 = '防喘振控制器',
    CustomUserLogic2 = 'ITCC压缩机升速',
    CustomUserLogic3 = '轴系监测'
  }
  /** 图形/连线分类 */
  export const enum GraphType {
    Node = 'Node',
    Edge = 'Edge',
    Image = 'Image'
  }
  /** 传感器节点名称 */
  export const enum ModelSensorNodeName {
    TSensor = '温度传感器',
    PSensor = '压力传感器',
    LSensor = '液位传感器',
    CompSensor = '组分传感器',
    FSensor = '流量传感器',
    NvfSensor = '标准体积流量传感器',
    VfSensor = '体积流量传感器',
    DSensor = '密度传感器'
  }
  /** 节点类型核心枚举 */
  export const enum NodeType {
    Material = 'Material',
    Energy = 'Energy',
    Valve = 'Valve',
    MixerTee = 'MixerTee',
    Seperator = 'Seperator',
    SimpleDistTower = 'SimpleDistTower',
    Pump = 'Pump',
    HeatX = 'HeatX',
    AirCooler = 'AirCooler',
    ConversionReactor = 'ConversionReactor',
    Furnace = 'Furnace',
    Pipe = 'Pipe',
    CentrifugalCompressor = 'CentrifugalCompressor',
    Signal = 'Signal',
    ByPass = 'ByPass',
    Vote = 'Vote',
    Rs = 'Rs',
    Not = 'Not',
    AndOr = 'AndOr',
    Delay = 'Delay',
    Pulse = 'Pulse',
    PositionInformation = 'PositionInformation',
    CustomVueNode = 'CustomVueNode',
    Aiuo = 'Aiuo',
    TSensor = 'TSensor',
    PSensor = 'PSensor',
    LSensor = 'LSensor',
    CompSensor = 'CompSensor',
    FSensor = 'FSensor',
    NvfSensor = 'NvfSensor',
    VfSensor = 'VfSensor',
    DSensor = 'DSensor',
    Cutter = 'Cutter',
    Rect = 'Rect',
    Ellipse = 'Ellipse',
    Path = 'Path',
    Text = 'Text',
    ScriptLogic = 'ScriptLogic',
    ScriptUO = 'ScriptUO',
    CustomCustomerUO = 'CustomCustomerUO',
    CustomUserUO = 'CustomUserUO',
    CustomSpecialUO = 'CustomSpecialUO',
    CustomUserLogic0 = 'CustomUserLogic0',
    CustomUserLogic1 = 'CustomUserLogic1',
    CustomUserLogic2 = 'CustomUserLogic2',
    CustomUserLogic3 = 'CustomUserLogic3'
  }
  /** 自定义模块前缀 */
  export const enum NodeTypeCustom {
    CustomCustomerUO = 'CustomCustomerUO',
    CustomUserUO = 'CustomUserUO',
    CustomSpecialUO = 'CustomSpecialUO',
    CustomSysUO = 'CustomSysUO',
    CustomUserLogic = 'CustomUserLogic',
    CustomCustomerLogic = 'CustomCustomerLogic',
    CustomSysLogic = 'CustomSysLogic'
  }
}

export declare namespace nameGenerator {
  export function getUsedNameDetailApi(code: string, modelId: string): Promise<NameGenDTO>
  export interface NameGenDTO {
    id: number
    code: string
    numberSegment: string
    modelId: string
  }
  export function saveOrUpdateNameGenApi(code: string, numberSegment: string, modelId: string): Promise<void>
  export function updateNameSegmentByDeleteApi(code: string, numberDelete: string, modelId: string): Promise<void>
  export function updateNameSegmentByNameNumberApi(code: string, numberNumber: string, modelId: string): Promise<void>
}

export declare namespace physicalBinarySync {
  /** 批量查询接口 */
  export function queryBinaryDataApi(funcCode: string, ids: Array<string>): Promise<Array<any>>
  /** 批量同步接口 */
  export function syncBinaryDataApi(funcCode: string, data: Array<any>): Promise<void>
}

export declare namespace physicalCalc {
  /** 定一个整体联合查询的返回结果 */
  export interface CalcAllDetailDTO {
    basePropertyCode: string
    basePropertyId: number
    basePropertyName: string
    basePropertyKey: string
    basePropertyPhase: string
    basePropertyMixture: number
    calcFunctionCode: string
  }
  export interface CalcFunctionDTO {
    id: number
    name: string
    code: string
    argsJson: string
    isShow: number
  }
  /** 根据 ID 列表批量查询方法 */
  export function getAllPpCalcFunctionByIdsApi(ids: Array<number>): Promise<Array<CalcFunctionDTO>>
  /** 根据 Code 列表批量查询方法 */
  export function getFirstPpCalcFunctionByCodesApi(codes: Array<string>): Promise<Array<CalcFunctionDTO>>
  /** 根据方法 ID 获取流体包详细关联信息 */
  export function getFluidPackageAllBpByFunctionIdApi(functionId: number): Promise<Array<CalcAllDetailDTO>>
  /** 获取所有方法列表 */
  export function getPpCalcFunctionListApi(): Promise<Array<CalcFunctionDTO>>
  /** 根据 BasePhysicalId 获取 Function 选项 (用于下拉框) */
  export function getPpFunctionOptionsByBpIdApi(bpId: number): Promise<Array<FunctionOptionDTO>>
  /**
   * 批量初始化/同步物性计算相关消息数据
   * data_type: "basePhysical" | "function" | "relation"
   */
  export function initPpCalcAllMsgDataApi(dataType: string, data: Array<any>): Promise<void>
}

export declare namespace physicalComponent {
  /** 获取库中所有的组分信息列表 */
  export function getAllPhysicalInformationListApi(): Promise<Array<PhysicalInformationDTO>>
  /** 根据组分 ID (compound_id) 读取相关记录 */
  export function getPhysicalBaseByCompoundIdApi(compoundId: number): Promise<Array<PhysicalBaseDTO>>
  /** 根据 ID 列表批量获取组分基础物理性质 */
  export function getPhysicalBaseByIdsApi(ids: Array<number>): Promise<Array<PhysicalBaseDTO>>
  /** 根据 casNo 列表批量获取组分详细信息 */
  export function getPhysicalInformationListByCasNoListApi(casNoList: Array<string>): Promise<Array<PhysicalInformationDTO>>
  /** 根据 casNo 获取单条组分详细信息 */
  export function getPhysicalInformationOneByCasNoApi(casNo: string): Promise<PhysicalInformationDTO>
  /** 根据组分 ID (compound_id) 获取其所有的温度关联方程 */
  export function getPhysicalTemperatureEquationByCompoundIdApi(compoundId: number): Promise<Array<TemperatureEquationDTO>>
  /** 根据 ID 列表获取组分温度关联方程记录 */
  export function getPhysicalTemperatureEquationByIdsApi(ids: Array<number>): Promise<Array<TemperatureEquationDTO>>
  /** 快速初始化组分基础性质数据 (全量删除并重新分段插入) */
  export function initPhysicalBaseDataFastApi(initJsonData: Array<any>): Promise<void>
  /** 快速初始化组分信息数据 (全量清空并分段插入) */
  export function initPhysicalInformationDataFastApi(initJsonData: Array<any>): Promise<void>
  /** 快速初始化温度关联方程数据 (全量物理删除并分段插入) */
  export function initPhysicalTemperatureEquationDataFastApi(initJsonData: Array<any>): Promise<void>
  export interface PhysicalBaseDTO {
    id: number
    componentId: number
    code: string
    name: string
    refId: number
    value: number
    unitType: string
    isDefault: number
    isShow: number
  }
  export interface PhysicalInformationDTO {
    id: number
    name: string
    formula: string
    casNo: string
    number: number
    internalName: string
  }
  export interface TemperatureEquationDTO {
    id: number
    componentId: number
    code: string
    name: string
    unit: string
    functionCode: number
    functionName: string
    coefficientA: number
    coefficientB: number
    coefficientC: number
    coefficientD: number
    coefficientE: number
    coefficientF: number
    coefficientG: number
    coefficientH: number
    coefficientK: number
    coefficientL: number
    minApplicableTemperature: number
    minApplicableTemperatureUnit: string
    maxApplicableTemperature: number
    maxApplicableTemperatureUnit: string
    isDefault: number
    isShow: number
  }
}

export declare namespace pointInfor {
  /** 查询所有点位信息 (返回 JSON 字符串) */
  export function getPositionInformationCacheAllMessageApi(): Promise<Array<PositionData>>
  /** 根据 type_num 列表查询点位信息 (返回 JSON 字符串) */
  export function getPositionInformationCacheByTypesApi(types: Array<number>): Promise<Array<PositionData>>
  export interface PositionData {
    name: string
    nameDisplay: string
    typeName: string
    typeNum: number
  }
  /** 批量更新或插入点位信息 */
  export function updateOrInsertPositionInformationCacheApi(data: Array<PositionData>): Promise<void>
}

export declare namespace shutterHandle {
  /**
   * 删除快照信息 (deleteModelShutterEntity)
   * 签名: (id: string, modelId: string) => Promise<number> (返回 rows_affected)
   */
  export function deleteShutterEntity(id: string, modelId: string): Promise<number>
  export interface FullShutterData {
    id: string
    name: string
    indexNum: number
    modelId: string
    objects: string
    sysvars: string
    updateAt: string
    baseStateCode: string
    userName?: string
    stateIndex?: number
    stateDesc?: string
    typeNum?: number
  }
  export interface FullShutterModel {
    id: string
    name: string
    indexNum: number
    updateAt: string
    objects: string
    sysvars: string
    modelId: string
    userName?: string
    typeNum?: number
    stateIndex?: number
    stateDesc?: string
    baseStateCode: string
  }
  export function getAllShutterEntityDetailList(modelId: string): Promise<Array<FullShutterModel>>
  export function getAllShutterEntityList(modelId: string): Promise<Array<ShutterListItem>>
  export function getShutterEntityById(id: string, modelId: string): Promise<FullShutterData | null>
  export function getShutterEntityByIdOnly(id: string): Promise<FullShutterData | null>
  /** 创建/更新快照信息 (insertModelShutterEntity) */
  export function insertShutterEntity(data: FullShutterData, modelId: string): Promise<number>
  export function insertShutterEntityOnly(data: FullShutterData): Promise<void>
  export interface ShutterListItem {
    id: string
    name: string
    updateAt: string
    indexNum: number
    baseStateCode: string
  }
  export function updateShutterEntity(data: FullShutterData, modelId: string): Promise<number>
  /**
   * 根据 ID 更新部分信息 (updateModelShutterEntityByIndexOnly)
   * 签名: (id: string, objects: string, sysvars: string, status: string) => Promise<number> (返回 rows_affected)
   */
  export function updateShutterEntityByIdOnly(id: string, objects: string, sysvars: string, status: string): Promise<number>
}

export declare namespace undoRedoHandle {
  /** 增加一条记录 */
  export function addUndoLog(opType: string, tableName: string, oldData: string, newData: string, modelId: string): Promise<number>
  /** 清除已经使用过的信息，防止来回操作 */
  export function deleteUndoLogsById(id: number, modelId: string): Promise<boolean>
  /** 清除所有回撤记录 */
  export function deleteUndoLogsByModelId(modelId: string): Promise<boolean>
  export function getTheLastRedoModel(modelId: string): Promise<UndoRedoData>
  export function getTheLastUndoModel(modelId: string): Promise<UndoRedoData>
  /** 根据modelId获取撤回操作的所有信息 */
  export function listUndoLogs(modelId: string): Promise<Array<UndoRedoData>>
  export function test(): Promise<void>
  export interface UndoRedoData {
    id: number
    opType: string
    tableName: string
    oldData: string
    newData: string
    modelId: string
  }
  /** 更新一条信息状态 */
  export function updateUndoNewData(id: number, modelId: string, newData: string): Promise<void>
  /** 更新 状态，用于处理下一步操作 */
  export function updateUndoStatus(id: number, modelId: string, status: number): Promise<void>
}

export declare namespace variableCurveHandle {
  /** 插入新的变量曲线信息 */
  export function addVariableCurveLog(datasets: Array<DatasetItem>, modelId: string, configId: string, simTime: number): Promise<number>
  export interface CurveModel {
    id: number
    simTime: string
    datasets: string
    createAt: string
    modelId: string
    configId: string
  }
  export interface DatasetItem {
    id: string
    name: string
    value: string
  }
  /** 根据 modelId, configId 和时间间隔 filterCount 获取过滤后的曲线数据 */
  export function listVariableCurvesByFilterCount(modelId: string, configId: string, filterCount: number): Promise<Array<CurveModel>>
  /** 根据 modelId 和 configId 获取所有曲线数据，按时间排序 */
  export function listVariableCurvesByTime(modelId: string, configId: string): Promise<Array<CurveModel>>
}
