//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "model_pf_var_default_params_entity")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub model_id: String,
    pub name: String,
    pub delta_max: String,
    pub min: String,
    pub max: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
