//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

use serde::{Deserialize, Serialize};
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize)]
#[sea_orm(table_name = "model_fluid_package_binary_rk_entity")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub fluid_package_id: String,
    pub compound_i: String,
    pub compound_i_name: String,
    pub compound_j: String,
    pub compound_j_name: String,
    #[sea_orm(column_name = "KAIJ")]
    pub kaij: String,
    #[sea_orm(column_name = "KBIJ")]
    pub kbij: String,
    #[sea_orm(column_name = "KCIJ")]
    pub kcij: String,
    pub min_t: String,
    pub max_t: String,
    pub is_default: i32,
    pub is_default_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
