//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Deserialize, Serialize)]
#[sea_orm(table_name = "model_fluid_package_binary_nrtl_entity")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub fluid_package_id: String,
    pub compound_i: String,
    pub compound_i_name: String,
    pub compound_j: String,
    pub compound_j_name: String,
    #[sea_orm(column_name = "AIJ")]
    pub aij: String,
    #[sea_orm(column_name = "AJI")]
    pub aji: String,
    #[sea_orm(column_name = "BIJ")]
    pub bij: String,
    #[sea_orm(column_name = "BJI")]
    pub bji: String,
    #[sea_orm(column_name = "CIJ")]
    pub cij: String,
    #[sea_orm(column_name = "DIJ")]
    pub dij: String,
    #[sea_orm(column_name = "EIJ")]
    pub eij: String,
    #[sea_orm(column_name = "EJI")]
    pub eji: String,
    #[sea_orm(column_name = "FIJ")]
    pub fij: String,
    #[sea_orm(column_name = "FJI")]
    pub fji: String,
    pub min_t: String,
    pub max_t: String,
    pub is_default: i32,
    pub is_default_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
