//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "model_status_params_entity")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub model_id: String,
    #[sea_orm(column_type = "Text")]
    pub init_params: String,
    pub graphic_id: String,
    pub code: String,
    pub r#type: String,
    pub name: String,
    pub status: i32,
    pub actived: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
