use crate::service_database::{
    database_business::entity::fluid_package::model_fluid_package_binary_handle::*,
    until_handle::drop_tables,
};
use sea_orm_migration::prelude::*;
#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(ModelModel::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ModelModel::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ModelModel::ModelNo)
                            .string()
                            .default("")
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelModel::Developer)
                            .string()
                            .default("")
                            .not_null(),
                    )
                    .col(ColumnDef::new(ModelModel::ModelName).string().not_null())
                    .col(
                        ColumnDef::new(ModelModel::StandardTemperature)
                            .double()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelModel::StandardTemperatureUnit)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelModel::StandardPressure)
                            .double()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelModel::StandardPressureUnit)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ModelModel::GridState).string().not_null())
                    .col(ColumnDef::new(ModelModel::GridColor).string().not_null())
                    .col(ColumnDef::new(ModelModel::GridSize).integer().not_null())
                    .col(
                        ColumnDef::new(ModelModel::CreateAt)
                            .date_time()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(ModelModel::UpdateAt)
                            .date_time()
                            .default(Expr::current_timestamp()),
                    )
                    .col(ColumnDef::new(ModelModel::Status).integer().not_null())
                    .col(
                        ColumnDef::new(ModelModel::DefaultModelId)
                            .string()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(ModelConfig::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ModelConfig::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ModelConfig::PropertyParams)
                            .text()
                            .default("")
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelConfig::ControlParams)
                            .text()
                            .default("")
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelConfig::RateParams)
                            .text()
                            .default("")
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelConfig::FlashParams)
                            .text()
                            .default("")
                            .not_null(),
                    )
                    .col(ColumnDef::new(ModelConfig::ModelId).string().not_null())
                    .col(
                        ColumnDef::new(ModelConfig::ModelState)
                            .integer()
                            .default(0)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelConfig::FilterLabelParams)
                            .text()
                            .default("")
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelConfig::RangeStatus)
                            .integer()
                            .default(1)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelConfig::ShowLabelParams)
                            .text()
                            .default("")
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelConfig::AutoShutterParams)
                            .text()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ModelConfig::OilParams).text().not_null())
                    .col(
                        ColumnDef::new(ModelConfig::RelatePoint)
                            .string()
                            .default("1")
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelConfig::RelateInterlock)
                            .string()
                            .default("1")
                            .not_null(),
                    )
                    .col(ColumnDef::new(ModelConfig::DefaultParams).text().not_null())
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(ModelSystemVariable::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ModelSystemVariable::Id)
                            .string()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ModelSystemVariable::ModelId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelSystemVariable::Name)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelSystemVariable::Code)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelSystemVariable::Value)
                            .double()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelSystemVariable::SortId)
                            .integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        // 创建 UnitSet 表
        manager
            .create_table(
                Table::create()
                    .table(ModelUnitSet::Table)
                    .if_not_exists()
                    .col(ColumnDef::new(ModelUnitSet::Id).string().primary_key())
                    .col(ColumnDef::new(ModelUnitSet::ModelId).string().not_null())
                    .col(ColumnDef::new(ModelUnitSet::EnName).string().not_null())
                    .col(ColumnDef::new(ModelUnitSet::Name).string().not_null())
                    .col(ColumnDef::new(ModelUnitSet::Code).string().not_null())
                    .col(
                        ColumnDef::new(ModelUnitSet::Status)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(ColumnDef::new(ModelUnitSet::IsDefault).integer().not_null())
                    .to_owned(),
            )
            .await?;

        // 创建 UnitItem 表
        manager
            .create_table(
                Table::create()
                    .table(ModelUnitItem::Table)
                    .if_not_exists()
                    .col(ColumnDef::new(ModelUnitItem::Id).string().primary_key())
                    .col(ColumnDef::new(ModelUnitItem::SetId).string().not_null())
                    .col(ColumnDef::new(ModelUnitItem::ModelId).string().not_null())
                    .col(ColumnDef::new(ModelUnitItem::Code).string().not_null())
                    .col(ColumnDef::new(ModelUnitItem::Value).string().not_null())
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(ModelNameGenerator::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ModelNameGenerator::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(ModelNameGenerator::Code).string().not_null())
                    .col(
                        ColumnDef::new(ModelNameGenerator::NumberSegment)
                            .string()
                            .not_null(),
                    ) // 对应 TS 中的 numberSegment
                    .col(
                        ColumnDef::new(ModelNameGenerator::ModelId)
                            .string()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(ModelCompoundChannel::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ModelCompoundChannel::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundChannel::RefName)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundChannel::Name)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundChannel::ModelId)
                            .string()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(ModelCompoundAllDetail::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ModelCompoundAllDetail::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundAllDetail::SourceId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundAllDetail::SourceType)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundAllDetail::Name)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundAllDetail::Formula)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundAllDetail::CasNo)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundAllDetail::BaseCasNo)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundAllDetail::Number)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundAllDetail::InternalName)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundAllDetail::SortNum)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundAllDetail::CompoundChannelId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundAllDetail::BasePhysicalProperty)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundAllDetail::TemperatureEquationProprety)
                            .text()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(ModelCompoundHenry::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ModelCompoundHenry::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(ModelCompoundHenry::Name).string().not_null())
                    .col(
                        ColumnDef::new(ModelCompoundHenry::CompoundChannelId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundHenry::CompoundDetailIds)
                            .string()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(ModelCompoundHenryDetail::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ModelCompoundHenryDetail::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundHenryDetail::IsDefaultId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundHenryDetail::ComponentIId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundHenryDetail::ComponentI)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundHenryDetail::ComponentJId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundHenryDetail::ComponentJ)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundHenryDetail::SourceName)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundHenryDetail::Aij)
                            .double()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundHenryDetail::Bij)
                            .double()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundHenryDetail::Cij)
                            .double()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundHenryDetail::Dij)
                            .double()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundHenryDetail::Eij)
                            .double()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundHenryDetail::Tlower)
                            .double()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundHenryDetail::Tupper)
                            .double()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundHenryDetail::IsDefault)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundHenryDetail::CompoundHenryId)
                            .string()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(ModelCompoundOil::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ModelCompoundOil::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundOil::CompoundChannelId)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ModelCompoundOil::Name).string().not_null())
                    .col(
                        ColumnDef::new(ModelCompoundOil::InternalName)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundOil::Formula)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ModelCompoundOil::CasNo).string().not_null())
                    .col(ColumnDef::new(ModelCompoundOil::Group).integer().not_null())
                    .col(
                        ColumnDef::new(ModelCompoundOil::BasePhysicalProperty)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundOil::DefaultPhysicalProperty)
                            .text()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelCompoundOil::TemperatureEquationProperty)
                            .text()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(ModelPfModelParams::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ModelPfModelParams::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ModelPfModelParams::ModelId)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ModelPfModelParams::Code).string().not_null())
                    .col(ColumnDef::new(ModelPfModelParams::Name).string().not_null())
                    .col(
                        ColumnDef::new(ModelPfModelParams::SolverType)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ModelPfModelParams::Params).text().not_null())
                    .col(
                        ColumnDef::new(ModelPfModelParams::DefaultId)
                            .integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(ModelPfVarParams::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ModelPfVarParams::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ModelPfVarParams::ModelId)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ModelPfVarParams::Name).string().not_null())
                    .col(
                        ColumnDef::new(ModelPfVarParams::DeltaMax)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ModelPfVarParams::Min).string().not_null())
                    .col(ColumnDef::new(ModelPfVarParams::Max).string().not_null())
                    .to_owned(),
            )
            .await?;
        // 1. 流体包主表
        manager
            .create_table(
                Table::create()
                    .table(ModelFluidPackage::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ModelFluidPackage::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(ModelFluidPackage::Name).string().not_null())
                    .col(
                        ColumnDef::new(ModelFluidPackage::ModelId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelFluidPackage::CompoundChannelId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelFluidPackage::CompoundHenryId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelFluidPackage::PropertyMethodId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelFluidPackage::IsDefault)
                            .integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        // 2. 物性计算详情表
        manager
            .create_table(
                Table::create()
                    .table(ModelPhysicalPropertyCalc::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ModelPhysicalPropertyCalc::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ModelPhysicalPropertyCalc::PhysicalPropertyName)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelPhysicalPropertyCalc::PhysicalPropertyId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelPhysicalPropertyCalc::FluidPackageId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelPhysicalPropertyCalc::PhysicalPropertyCode)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelPhysicalPropertyCalc::CalcCode)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelPhysicalPropertyCalc::DefaultCalcCode)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelPhysicalPropertyCalc::Key)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelPhysicalPropertyCalc::Phase)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelPhysicalPropertyCalc::Mixture)
                            .integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        // --- 1. NRTL & NRTL_RK (结构完全一致) ---
        let nrtl_tables = [BinaryTables::Nrtl, BinaryTables::NrtlRk];
        for table in nrtl_tables {
            manager
                .create_table(
                    Table::create()
                        .table(table)
                        .if_not_exists()
                        .col(
                            ColumnDef::new(BinaryCols::Id)
                                .string()
                                .not_null()
                                .primary_key(),
                        )
                        .col(
                            ColumnDef::new(BinaryCols::FluidPackageId)
                                .string()
                                .not_null(),
                        )
                        .col(ColumnDef::new(BinaryCols::CompoundI).string().not_null())
                        .col(
                            ColumnDef::new(BinaryCols::CompoundIName)
                                .string()
                                .not_null(),
                        )
                        .col(ColumnDef::new(BinaryCols::CompoundJ).string().not_null())
                        .col(
                            ColumnDef::new(BinaryCols::CompoundJName)
                                .string()
                                .not_null(),
                        )
                        .col(ColumnDef::new(BinaryCols::Aij).string().not_null())
                        .col(ColumnDef::new(BinaryCols::Aji).string().not_null())
                        .col(ColumnDef::new(BinaryCols::Bij).string().not_null())
                        .col(ColumnDef::new(BinaryCols::Bji).string().not_null())
                        .col(ColumnDef::new(BinaryCols::Cij).string().not_null())
                        .col(ColumnDef::new(BinaryCols::Dij).string().not_null())
                        .col(ColumnDef::new(BinaryCols::Eij).string().not_null())
                        .col(ColumnDef::new(BinaryCols::Eji).string().not_null())
                        .col(ColumnDef::new(BinaryCols::Fij).string().not_null())
                        .col(ColumnDef::new(BinaryCols::Fji).string().not_null())
                        .col(ColumnDef::new(BinaryCols::MinT).string().not_null())
                        .col(ColumnDef::new(BinaryCols::MaxT).string().not_null())
                        .col(ColumnDef::new(BinaryCols::IsDefault).integer().not_null())
                        .col(ColumnDef::new(BinaryCols::IsDefaultId).string().not_null())
                        .to_owned(),
                )
                .await?;
        }

        // --- 2. PR, RK, SRK (结构完全一致，含 KAIJ, KBIJ, KCIJ) ---
        let eos_tables = [BinaryTables::Pr, BinaryTables::Rk, BinaryTables::Srk];
        for table in eos_tables {
            manager
                .create_table(
                    Table::create()
                        .table(table)
                        .if_not_exists()
                        .col(
                            ColumnDef::new(BinaryCols::Id)
                                .string()
                                .not_null()
                                .primary_key(),
                        )
                        .col(
                            ColumnDef::new(BinaryCols::FluidPackageId)
                                .string()
                                .not_null(),
                        )
                        .col(ColumnDef::new(BinaryCols::CompoundI).string().not_null())
                        .col(
                            ColumnDef::new(BinaryCols::CompoundIName)
                                .string()
                                .not_null(),
                        )
                        .col(ColumnDef::new(BinaryCols::CompoundJ).string().not_null())
                        .col(
                            ColumnDef::new(BinaryCols::CompoundJName)
                                .string()
                                .not_null(),
                        )
                        .col(ColumnDef::new(BinaryCols::Kaij).string().not_null())
                        .col(ColumnDef::new(BinaryCols::Kbij).string().not_null())
                        .col(ColumnDef::new(BinaryCols::Kcij).string().not_null())
                        .col(ColumnDef::new(BinaryCols::MinT).string().not_null())
                        .col(ColumnDef::new(BinaryCols::MaxT).string().not_null())
                        .col(ColumnDef::new(BinaryCols::IsDefault).integer().not_null())
                        .col(ColumnDef::new(BinaryCols::IsDefaultId).string().not_null())
                        .to_owned(),
                )
                .await?;
        }

        // --- 3. PSRK (含 TIJ, TJI, VIJ, VJI) ---
        manager
            .create_table(
                Table::create()
                    .table(BinaryTables::Psrk)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(BinaryCols::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(BinaryCols::FluidPackageId)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(BinaryCols::CompoundI).string().not_null())
                    .col(
                        ColumnDef::new(BinaryCols::CompoundIName)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(BinaryCols::CompoundJ).string().not_null())
                    .col(
                        ColumnDef::new(BinaryCols::CompoundJName)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(BinaryCols::Tij).string().not_null())
                    .col(ColumnDef::new(BinaryCols::Tji).string().not_null())
                    .col(ColumnDef::new(BinaryCols::Vij).string().not_null())
                    .col(ColumnDef::new(BinaryCols::Vji).string().not_null())
                    .col(ColumnDef::new(BinaryCols::IsDefault).integer().not_null())
                    .col(ColumnDef::new(BinaryCols::IsDefaultId).string().not_null())
                    .to_owned(),
            )
            .await?;

        // --- 4. UNIQUAC (参数最多，含 CJI, DJI 等) ---
        manager
            .create_table(
                Table::create()
                    .table(BinaryTables::Uniquac)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(BinaryCols::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(BinaryCols::FluidPackageId)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(BinaryCols::CompoundI).string().not_null())
                    .col(
                        ColumnDef::new(BinaryCols::CompoundIName)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(BinaryCols::CompoundJ).string().not_null())
                    .col(
                        ColumnDef::new(BinaryCols::CompoundJName)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(BinaryCols::Aij).string().not_null())
                    .col(ColumnDef::new(BinaryCols::Aji).string().not_null())
                    .col(ColumnDef::new(BinaryCols::Bij).string().not_null())
                    .col(ColumnDef::new(BinaryCols::Bji).string().not_null())
                    .col(ColumnDef::new(BinaryCols::Cij).string().not_null())
                    .col(ColumnDef::new(BinaryCols::Cji).string().not_null())
                    .col(ColumnDef::new(BinaryCols::Dij).string().not_null())
                    .col(ColumnDef::new(BinaryCols::Dji).string().not_null())
                    .col(ColumnDef::new(BinaryCols::Eij).string().not_null())
                    .col(ColumnDef::new(BinaryCols::Eji).string().not_null())
                    .col(ColumnDef::new(BinaryCols::Fij).string().not_null())
                    .col(ColumnDef::new(BinaryCols::Fji).string().not_null())
                    .col(ColumnDef::new(BinaryCols::MinT).string().not_null())
                    .col(ColumnDef::new(BinaryCols::MaxT).string().not_null())
                    .col(ColumnDef::new(BinaryCols::IsDefault).integer().not_null())
                    .col(ColumnDef::new(BinaryCols::IsDefaultId).string().not_null())
                    .to_owned(),
            )
            .await?;

        // --- 5. Wilson (结构与 UNIQUAC 类似但略少字段) ---
        manager
            .create_table(
                Table::create()
                    .table(BinaryTables::Wilson)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(BinaryCols::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(BinaryCols::FluidPackageId)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(BinaryCols::CompoundI).string().not_null())
                    .col(
                        ColumnDef::new(BinaryCols::CompoundIName)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(BinaryCols::CompoundJ).string().not_null())
                    .col(
                        ColumnDef::new(BinaryCols::CompoundJName)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(BinaryCols::Aij).string().not_null())
                    .col(ColumnDef::new(BinaryCols::Aji).string().not_null())
                    .col(ColumnDef::new(BinaryCols::Bij).string().not_null())
                    .col(ColumnDef::new(BinaryCols::Bji).string().not_null())
                    .col(ColumnDef::new(BinaryCols::Cij).string().not_null())
                    .col(ColumnDef::new(BinaryCols::Cji).string().not_null())
                    .col(ColumnDef::new(BinaryCols::Dij).string().not_null())
                    .col(ColumnDef::new(BinaryCols::Dji).string().not_null())
                    .col(ColumnDef::new(BinaryCols::Eij).string().not_null())
                    .col(ColumnDef::new(BinaryCols::Eji).string().not_null())
                    .col(ColumnDef::new(BinaryCols::MinT).string().not_null())
                    .col(ColumnDef::new(BinaryCols::MaxT).string().not_null())
                    .col(ColumnDef::new(BinaryCols::IsDefault).integer().not_null())
                    .col(ColumnDef::new(BinaryCols::IsDefaultId).string().not_null())
                    .to_owned(),
            )
            .await?;

        manager
            .create_table(
                Table::create()
                    .table(ModelReactionPackage::Table)
                    .if_not_exists()
                    // 对应实体中的 id: String (primary_key)
                    .col(
                        ColumnDef::new(ModelReactionPackage::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    // 对应 reaction_name
                    .col(
                        ColumnDef::new(ModelReactionPackage::ReactionName)
                            .string()
                            .not_null(),
                    )
                    // 对应 model_id
                    .col(
                        ColumnDef::new(ModelReactionPackage::ModelId)
                            .string()
                            .not_null(),
                    )
                    // 对应 compound_channel_id
                    .col(
                        ColumnDef::new(ModelReactionPackage::CompoundChannelId)
                            .string()
                            .not_null(),
                    )
                    // 对应 fluid_package_ids
                    .col(
                        ColumnDef::new(ModelReactionPackage::FluidPackageIds)
                            .string()
                            .not_null(),
                    )
                    // 对应 reaction_package_type
                    .col(
                        ColumnDef::new(ModelReactionPackage::ReactionPackageType)
                            .string()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // 显式标注类型，确保不同实体的 Table 都能放入同一个数组
        let all_tables: &[&(dyn Iden + Sync)] = &[
            &ModelModel::Table,
            &ModelConfig::Table,
            &ModelSystemVariable::Table,
            &ModelUnitItem::Table,
            &ModelUnitSet::Table,
            &ModelNameGenerator::Table,
            &ModelCompoundChannel::Table,
            &ModelCompoundAllDetail::Table,
            &ModelCompoundHenry::Table,
            &ModelCompoundHenryDetail::Table,
            &ModelCompoundOil::Table,
            &ModelPfModelParams::Table,
            &ModelPfVarParams::Table,
            &ModelPhysicalPropertyCalc::Table,
            &ModelFluidPackage::Table,
            &ModelReactionPackage::Table,
        ];

        // 调用统一删除逻辑
        drop_tables(manager, all_tables).await?;

        let all_tables = [
            BinaryTables::Nrtl,
            BinaryTables::NrtlRk,
            BinaryTables::Pr,
            BinaryTables::Psrk,
            BinaryTables::Rk,
            BinaryTables::Srk,
            BinaryTables::Uniquac,
            BinaryTables::Wilson,
        ];
        for table in all_tables {
            manager
                .drop_table(Table::drop().table(table).to_owned())
                .await?;
        }
        Ok(())
    }
}

#[derive(Iden)]
enum ModelModel {
    Table,
    Id,
    ModelNo,
    Developer,
    ModelName,
    StandardTemperature,
    StandardTemperatureUnit,
    StandardPressure,
    StandardPressureUnit,
    GridState,
    GridColor,
    GridSize,
    CreateAt,
    UpdateAt,
    Status,
    DefaultModelId,
}

#[derive(Iden)]
enum ModelConfig {
    Table,
    Id,
    PropertyParams,
    ControlParams,
    RateParams,
    FlashParams,
    ModelId,
    ModelState,
    FilterLabelParams,
    RangeStatus,
    ShowLabelParams,
    AutoShutterParams,
    OilParams,
    RelatePoint,
    RelateInterlock,
    DefaultParams,
}
#[derive(Iden)]
enum ModelSystemVariable {
    Table,
    Id,
    ModelId,
    Name,
    Code,
    Value,
    SortId,
}

#[derive(Iden)]
enum ModelUnitSet {
    Table,
    Id,
    ModelId,
    EnName,
    Name,
    Code,
    Status,
    IsDefault,
}

#[derive(Iden)]
enum ModelUnitItem {
    Table,
    Id,
    SetId,
    ModelId,
    Code,
    Value,
}

#[derive(Iden)]
pub enum ModelNameGenerator {
    Table,
    Id,
    Code,
    NumberSegment, // 这里根据你的 Entity 定义，映射字段名
    ModelId,
}

#[derive(Iden)]
pub enum ModelCompoundChannel {
    Table,
    Id,
    RefName,
    Name,
    ModelId,
}

#[derive(Iden)]
pub enum ModelCompoundAllDetail {
    Table,
    Id,
    SourceId,
    SourceType,
    Name,
    Formula,
    CasNo,
    BaseCasNo,
    Number,
    #[iden = "internalName"]
    InternalName,
    #[iden = "sortNum"]
    SortNum,
    CompoundChannelId,
    BasePhysicalProperty,
    TemperatureEquationProprety,
}

#[derive(Iden)]
pub enum ModelCompoundHenry {
    Table,
    Id,
    Name,
    #[iden = "compoundChannel_id"]
    CompoundChannelId,
    #[iden = "compoundDetailIds"]
    CompoundDetailIds,
}
#[derive(Iden)]
pub enum ModelCompoundHenryDetail {
    Table,
    Id,
    #[iden = "isDefaultId"]
    IsDefaultId,
    ComponentIId,
    ComponentI,
    ComponentJId,
    ComponentJ,
    SourceName,
    Aij,
    Bij,
    Cij,
    Dij,
    Eij,
    Tlower,
    Tupper,
    IsDefault,
    CompoundHenryId,
}

#[derive(Iden)]
pub enum ModelCompoundOil {
    Table,
    Id,
    CompoundChannelId,
    Name,
    #[iden = "internalName"]
    InternalName,
    Formula,
    CasNo,
    Group,
    BasePhysicalProperty,
    DefaultPhysicalProperty,
    TemperatureEquationProperty,
}

#[derive(Iden)]
pub enum ModelPfModelParams {
    Table,
    Id,
    ModelId,
    Code,
    Name,
    SolverType,
    Params,
    DefaultId,
}

#[derive(Iden)]
pub enum ModelPfVarParams {
    #[iden = "model_pf_var_default_params_entity"]
    Table,
    Id,
    ModelId,
    Name,
    DeltaMax,
    Min,
    Max,
}

#[derive(Iden)]
pub enum ModelFluidPackage {
    Table,
    Id,
    Name,
    ModelId,
    CompoundChannelId,
    CompoundHenryId,
    PropertyMethodId,
    IsDefault,
}

#[derive(Iden)]
pub enum ModelPhysicalPropertyCalc {
    Table,
    Id,
    PhysicalPropertyName,
    PhysicalPropertyId,
    FluidPackageId,
    PhysicalPropertyCode,
    CalcCode,
    DefaultCalcCode,
    Key,
    Phase,
    Mixture,
}

#[derive(Iden)]
enum ModelReactionPackage {
    Table,
    Id,
    ReactionName,
    ModelId,
    CompoundChannelId,
    FluidPackageIds,
    ReactionPackageType,
}
