use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .create_table(
                Table::create()
                    .table(ModelModel::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ModelModel::Id)
                            .string()
                            .not_null()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ModelModel::ModelNo)
                            .string()
                            .default("")
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelModel::Developer)
                            .string()
                            .default("")
                            .not_null(),
                    )
                    .col(ColumnDef::new(ModelModel::ModelName).string().not_null())
                    .col(
                        ColumnDef::new(ModelModel::StandardTemperature)
                            .double()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelModel::StandardTemperatureUnit)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelModel::StandardPressure)
                            .double()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelModel::StandardPressureUnit)
                            .string()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ModelModel::GridState).string().not_null())
                    .col(ColumnDef::new(ModelModel::GridColor).string().not_null())
                    .col(ColumnDef::new(ModelModel::GridSize).integer().not_null())
                    .col(
                        ColumnDef::new(ModelModel::CreateAt)
                            .date_time()
                            .default(Expr::current_timestamp()),
                    )
                    .col(
                        ColumnDef::new(ModelModel::UpdateAt)
                            .date_time()
                            .default(Expr::current_timestamp()),
                    )
                    .col(ColumnDef::new(ModelModel::Status).integer().not_null())
                    .col(
                        ColumnDef::new(ModelModel::DefaultModelId)
                            .string()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(ModelConfig::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ModelConfig::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ModelConfig::PropertyParams)
                            .text()
                            .default("")
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelConfig::ControlParams)
                            .text()
                            .default("")
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelConfig::RateParams)
                            .text()
                            .default("")
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelConfig::FlashParams)
                            .text()
                            .default("")
                            .not_null(),
                    )
                    .col(ColumnDef::new(ModelConfig::ModelId).string().not_null())
                    .col(
                        ColumnDef::new(ModelConfig::ModelState)
                            .integer()
                            .default(0)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelConfig::FilterLabelParams)
                            .text()
                            .default("")
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelConfig::RangeStatus)
                            .integer()
                            .default(1)
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelConfig::ShowLabelParams)
                            .text()
                            .default("")
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelConfig::AutoShutterParams)
                            .text()
                            .not_null(),
                    )
                    .col(ColumnDef::new(ModelConfig::OilParams).text().not_null())
                    .col(
                        ColumnDef::new(ModelConfig::RelatePoint)
                            .string()
                            .default("1")
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelConfig::RelateInterlock)
                            .string()
                            .default("1")
                            .not_null(),
                    )
                    .col(ColumnDef::new(ModelConfig::DefaultParams).text().not_null())
                    .to_owned(),
            )
            .await?;
        manager
            .create_table(
                Table::create()
                    .table(ModelSystemVariable::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(ModelSystemVariable::Id)
                            .string()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(ModelSystemVariable::ModelId)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelSystemVariable::Name)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelSystemVariable::Code)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelSystemVariable::Value)
                            .double()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(ModelSystemVariable::SortId)
                            .integer()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;
        // 创建 UnitSet 表
        manager
            .create_table(
                Table::create()
                    .table(ModelUnitSet::Table)
                    .if_not_exists()
                    .col(ColumnDef::new(ModelUnitSet::Id).string().primary_key())
                    .col(ColumnDef::new(ModelUnitSet::ModelId).string().not_null())
                    .col(ColumnDef::new(ModelUnitSet::EnName).string().not_null())
                    .col(ColumnDef::new(ModelUnitSet::Name).string().not_null())
                    .col(ColumnDef::new(ModelUnitSet::Code).string().not_null())
                    .col(
                        ColumnDef::new(ModelUnitSet::Status)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(ColumnDef::new(ModelUnitSet::IsDefault).integer().not_null())
                    .to_owned(),
            )
            .await?;

        // 创建 UnitItem 表
        manager
            .create_table(
                Table::create()
                    .table(ModelUnitItem::Table)
                    .if_not_exists()
                    .col(ColumnDef::new(ModelUnitItem::Id).string().primary_key())
                    .col(ColumnDef::new(ModelUnitItem::SetId).string().not_null())
                    .col(ColumnDef::new(ModelUnitItem::ModelId).string().not_null())
                    .col(ColumnDef::new(ModelUnitItem::Code).string().not_null())
                    .col(ColumnDef::new(ModelUnitItem::Value).string().not_null())
                    .to_owned(),
            )
            .await?;
        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(Table::drop().table(ModelModel::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(ModelConfig::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(ModelSystemVariable::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(ModelUnitItem::Table).to_owned())
            .await?;
        manager
            .drop_table(Table::drop().table(ModelUnitSet::Table).to_owned())
            .await?;
        Ok(())
    }
}

#[derive(Iden)]
enum ModelModel {
    Table,
    Id,
    ModelNo,
    Developer,
    ModelName,
    StandardTemperature,
    StandardTemperatureUnit,
    StandardPressure,
    StandardPressureUnit,
    GridState,
    GridColor,
    GridSize,
    CreateAt,
    UpdateAt,
    Status,
    DefaultModelId,
}

#[derive(Iden)]
enum ModelConfig {
    Table,
    Id,
    PropertyParams,
    ControlParams,
    RateParams,
    FlashParams,
    ModelId,
    ModelState,
    FilterLabelParams,
    RangeStatus,
    ShowLabelParams,
    AutoShutterParams,
    OilParams,
    RelatePoint,
    RelateInterlock,
    DefaultParams,
}
#[derive(Iden)]
enum ModelSystemVariable {
    Table,
    Id,
    ModelId,
    Name,
    Code,
    Value,
    SortId,
}

#[derive(Iden)]
enum ModelUnitSet {
    Table,
    Id,
    ModelId,
    EnName,
    Name,
    Code,
    Status,
    IsDefault,
}

#[derive(Iden)]
enum ModelUnitItem {
    Table,
    Id,
    SetId,
    ModelId,
    Code,
    Value,
}
