//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "model_material_entity")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub model_id: String,
    pub name: String,
    pub r#type: String,
    pub actived: i32,
    #[sea_orm(column_name = "fluidPackage_id")]
    pub fluid_package_id: String,
    pub status: i32,
    pub create_at: String,
    #[sea_orm(column_name = "flashType")]
    pub flash_type: String,
    #[sea_orm(column_name = "pressureFixed")]
    pub pressure_fixed: i32,
    #[sea_orm(column_name = "flowFixed")]
    pub flow_fixed: i32,
    #[sea_orm(column_name = "pfDisconnected")]
    pub pf_disconnected: i32,
    #[sea_orm(column_name = "massFlow")]
    pub mass_flow: i32,
    #[sea_orm(column_type = "Text")]
    pub phases: String,
    #[sea_orm(column_type = "Text")]
    pub feed: String,
    #[sea_orm(column_type = "Text")]
    pub product: String,
    #[sea_orm(column_type = "Text")]
    pub script: String,
    pub current_mole_or_mass: String,
    pub copy_pruduct_form: i32,
    pub copy_feed_form: i32,
    pub feed_or_product_flash_type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
