//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "model_variable_choose_entity")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub r#type: String,
    pub model_id: String,
    pub graphic_source_id: String,
    pub connect_material_type: String,
    pub show_name: String,
    #[sea_orm(column_type = "Text")]
    pub filter_msg: String,
    pub unit_code: String,
    pub graphic_type: String,
    pub from_type: String,
    pub data_type: String,
    pub data_mode: String,
    pub dcs_name: String,
    pub value_name: String,
    pub sort: i32,
    pub y_max_value: Option<i32>,
    pub y_min_value: Option<i32>,
    pub information: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
