//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "model_compound_oil")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub compound_channel_id: String,
    pub name: String,
    #[sea_orm(column_name = "internalName")]
    pub internal_name: String,
    pub formula: String,
    pub cas_no: String,
    pub group: i32,
    #[sea_orm(column_type = "Text")]
    pub base_physical_property: String,
    #[sea_orm(column_type = "Text")]
    pub default_physical_property: String,
    #[sea_orm(column_type = "Text")]
    pub temperature_equation_property: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
