//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "model_model")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub model_no: String,
    pub developer: String,
    pub model_name: String,
    #[sea_orm(column_type = "Double")]
    pub standard_temperature: f64,
    pub standard_temperature_unit: String,
    #[sea_orm(column_type = "Double")]
    pub standard_pressure: f64,
    pub standard_pressure_unit: String,
    pub grid_state: String,
    pub grid_color: String,
    pub grid_size: i32,
    #[sea_orm(column_type = "custom(\"datetime\")")]
    pub create_at: String,
    #[sea_orm(column_type = "custom(\"datetime\")")]
    pub update_at: String,
    pub status: i32,
    pub default_model_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
