//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "model_config")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text")]
    pub property_params: String,
    #[sea_orm(column_type = "Text")]
    pub control_params: String,
    #[sea_orm(column_type = "Text")]
    pub rate_params: String,
    #[sea_orm(column_type = "Text")]
    pub flash_params: String,
    pub model_id: String,
    pub model_state: i32,
    #[sea_orm(column_type = "Text")]
    pub filter_label_params: String,
    pub range_status: i32,
    #[sea_orm(column_type = "Text")]
    pub show_label_params: String,
    #[sea_orm(column_type = "Text")]
    pub auto_shutter_params: String,
    #[sea_orm(column_type = "Text")]
    pub oil_params: String,
    pub relate_point: String,
    pub relate_interlock: String,
    #[sea_orm(column_type = "Text")]
    pub default_params: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
