//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "model_graphic_node_attributes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub graphic_page_id: String,
    pub model_id: String,
    #[sea_orm(column_name = "sourceId")]
    pub source_id: String,
    pub position: String,
    pub size: String,
    pub angle: i32,
    pub z_index: i32,
    pub parent: String,
    #[sea_orm(column_type = "Text")]
    pub children: String,
    #[sea_orm(column_type = "Text")]
    pub ports: String,
    pub shape: String,
    pub flip: i32,
    pub rotate: i32,
    pub relation_node_id: i32,
    pub point_name: String,
    pub point_type: i32,
    pub last_opened_tab: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
