//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "model_initialize_data_in_cold_state")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub model_id: String,
    pub material_object: String,
    pub fluid_package_id: String,
    #[sea_orm(column_type = "Text")]
    pub graphic_element_model_list: String,
    pub config_msg: String,
    pub is_default: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
