//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "model_logic_entity")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub model_id: String,
    pub name: String,
    pub r#type: String,
    pub actived: i32,
    #[sea_orm(column_type = "Text")]
    pub const_params: String,
    #[sea_orm(column_type = "Text")]
    pub params: String,
    #[sea_orm(column_name = "inputData", column_type = "Text")]
    pub input_data: String,
    #[sea_orm(column_name = "outputData", column_type = "Text")]
    pub output_data: String,
    pub status: i32,
    pub create_at: String,
    pub in_port_number: Option<i32>,
    #[sea_orm(column_type = "Text")]
    pub script: String,
    #[sea_orm(column_type = "Text")]
    pub comm_pv: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
