//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "model_compound_all_detail")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub source_id: String,
    pub source_type: String,
    pub name: String,
    pub formula: String,
    pub cas_no: String,
    pub base_cas_no: String,
    pub number: i32,
    #[sea_orm(column_name = "internalName")]
    pub internal_name: String,
    #[sea_orm(column_name = "sortNum")]
    pub sort_num: i32,
    pub compound_channel_id: String,
    #[sea_orm(column_type = "Text")]
    pub base_physical_property: String,
    #[sea_orm(column_type = "Text")]
    pub temperature_equation_proprety: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
