//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "model_reaction_detail")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub reaction_package_id: String,
    pub model_id: String,
    pub name: String,
    pub reaction_type: String,
    pub level: i32,
    pub equation: String,
    pub balance: String,
    pub reaction_heat: String,
    pub list: String,
    pub base_info: String,
    pub reaction_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
