//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "model_compound_henry_detail")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    #[sea_orm(column_name = "isDefaultId")]
    pub is_default_id: String,
    pub component_i_id: i32,
    pub component_i: String,
    pub component_j_id: i32,
    pub component_j: String,
    pub source_name: String,
    #[sea_orm(column_type = "Double")]
    pub aij: f64,
    #[sea_orm(column_type = "Double")]
    pub bij: f64,
    #[sea_orm(column_type = "Double")]
    pub cij: f64,
    #[sea_orm(column_type = "Double")]
    pub dij: f64,
    #[sea_orm(column_type = "Double")]
    pub eij: f64,
    #[sea_orm(column_type = "Double")]
    pub tlower: f64,
    #[sea_orm(column_type = "Double")]
    pub tupper: f64,
    pub is_default: i32,
    pub compound_henry_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
