//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "model_graphic_edge_attributes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub graphic_page_id: String,
    pub model_id: String,
    pub shape: String,
    pub source: String,
    pub target: String,
    #[sea_orm(column_name = "sourceId")]
    pub source_id: String,
    #[sea_orm(column_name = "zIndex")]
    pub z_index: i32,
    #[sea_orm(column_type = "Text")]
    pub vertices: String,
    pub label: String,
    #[sea_orm(column_type = "Text")]
    pub data: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
