//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.19

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "model_physical_property_calc_entity")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub physical_property_name: String,
    pub physical_property_id: String,
    pub fluid_package_id: String,
    pub physical_property_code: String,
    pub calc_code: String,
    pub default_calc_code: String,
    pub key: String,
    pub phase: String,
    pub mixture: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
